(() => {
 const API='https://api-production-c1a79.up.railway.app';
 const token=()=>sessionStorage.getItem('materialinsel-session')||'';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function call(path,data,method){
  const response=await fetch(API+path,{method:method||(data?'POST':'GET'),headers:{...(data?{'Content-Type':'application/json'}:{}),...(token()?{Authorization:'Bearer '+token()}:{})},...(data?{body:JSON.stringify(data)}:{})});
  const result=await response.json();if(!response.ok)throw Error(result.error||'Die Anfrage konnte nicht abgeschlossen werden.');return result;
 }
 const accountLink=document.querySelector('[data-account-link]');
 let current=null;
 async function loadUser(){if(!token())return null;try{current=(await call('/me')).user;if(accountLink)accountLink.textContent=current.role==='admin'?'Konto & Freischaltungen':'Mein Konto';return current;}catch(e){sessionStorage.removeItem('materialinsel-session');return null;}}
 const ready=loadUser();
 const returnToMap=()=>{const path=sessionStorage.getItem('materialinsel-return')||'';return /^\/(mappen|faecher|projekte|eltern-schueler)\//.test(path)?path:null;};
 document.addEventListener('click',async e=>{
  const link=e.target.closest('[data-protected]');if(!link)return;e.preventDefault();
  await ready;
  if(!token()){sessionStorage.setItem('materialinsel-return',location.pathname+location.hash);location.href='/konto/';return;}
  link.setAttribute('aria-busy','true');
  try{
   const r=await fetch(API+'/download/'+encodeURIComponent(link.dataset.protected),{headers:{Authorization:'Bearer '+token()}});
   if(!r.ok){const d=await r.json();if(r.status===402&&d.code==='purchase_required'){const tid=link.closest('.theme-menu')?.id;openPurchase(tid&&shop.products[tid]?tid:d.product,()=>link.click());return;}throw Error(d.error||'Download nicht möglich.');}
   const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=link.dataset.protected+'.pdf';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);
  }catch(err){showNotice(err.message);}finally{link.removeAttribute('aria-busy');}
 });

 // ---------- Shop: Mappen einzeln kaufen (PayPal) ----------
 let shop={enabled:false,products:{}},owned=new Set(),fileProduct={},fileProducts={},capacity={available:true};
 const ownsFile=f=>(fileProducts[f]||[]).some(q=>owned.has(q));
 // Persönliche Korrektur: Heft + Korrektur (<heft>-mit-korrektur) zählt auch als Kauf des Hefts
 const KORREKTUR='korrektur-selbstlernheft',BUNDLE=pid=>pid+'-mit-korrektur',FULL='Gerade ausgebucht – bitte morgen wieder versuchen.';
 const ownsP=pid=>owned.has(pid)||owned.has(BUNDLE(pid));
 const price=(c,cur)=>(c/100).toLocaleString('de-DE',{style:'currency',currency:cur||'EUR'});
 const shopReady=(async()=>{try{shop=await (await fetch(API+'/shop')).json();for(const [pid,p] of Object.entries(shop.products||{}))for(const f of p.files)(fileProducts[f]=fileProducts[f]||[]).push(pid),fileProduct[f]=fileProduct[f]||pid;}catch(e){}
  if(shop.products&&shop.products[KORREKTUR]&&document.querySelector('[data-product^="selbstlernheft-"],[data-korrektur-status],[data-buy="'+KORREKTUR+'"]')){try{capacity=await (await fetch(API+'/learning/capacity')).json();}catch(e){}}
  await ready;if(shop.enabled&&token()){try{owned=new Set((await call('/purchases')).products);}catch(e){}}decorate();korrekturStatus();})();
 function korrekturStatus(){document.querySelectorAll('[data-korrektur-status]').forEach(el=>{el.hidden=capacity.available!==false;el.textContent=capacity.available===false?FULL:'';});document.querySelectorAll('[data-buy="'+KORREKTUR+'"]').forEach(b=>{if(capacity.available===false)b.disabled=true;});}
 function decorate(){
  if(!shop.enabled)return;
  document.querySelectorAll('.theme-menu').forEach(theme=>{
   const first=theme.querySelector('[data-protected]');const pid=(shop.products[theme.id]&&theme.id)||(first&&fileProduct[first.dataset.protected]);if(!pid)return;
   if(theme.dataset.unlisted==='1'){if(ownsP(pid)){theme.dataset.owned='1';theme.hidden=false;}else return;}
   theme.querySelectorAll('[data-protected]').forEach(link=>{
    const canDownload=ownsP(pid)||ownsFile(link.dataset.protected)||current?.role==='admin';
    const action=canDownload?'Herunterladen ↓':token()?'Paket kaufen':'Anmelden zum Download';
    const label=link.querySelector('.download-action');if(label)label.textContent=action;
    link.title=canDownload?'Gekaufte Datei herunterladen':'Im Paket enthalten. Zum Download benötigst du ein Konto und den Kauf dieser Mappe.';
   });
   theme.querySelectorAll('[data-protected] .download-label').forEach(l=>{l.textContent=l.textContent.replace('mit Freischaltung',ownsP(pid)?'gekauft':'nach Kauf');});
   const summary=theme.querySelector(':scope>summary');if(summary&&!theme.classList.contains('product-detail')&&!summary.querySelector('.shop-price')){const tag=document.createElement('span');tag.className='shop-price';tag.textContent=owned.has(pid)?'✓ Gekauft':'Komplette Mappe · '+price(shop.products[pid].price,shop.products[pid].currency);summary.append(tag);}
   const box=theme.querySelector(':scope>div')||theme;if(box.querySelector('.shop-bar'))return;
   const bar=document.createElement('div');bar.className='shop-bar'+(ownsP(pid)?' is-owned':'');
   bar.innerHTML=(ownsP(pid)||current?.role==='admin')?'<strong>✓ Diese Mappe gehört dir.</strong> Alle Lehrkräfte- und Schülerdownloads dieser Mappe sind freigeschaltet.':`<div><strong>${esc(price(shop.products[pid].price,shop.products[pid].currency))} · Gesamtpaket</strong><small>Alle unten aufgeführten Dateien inklusive. Einmaliger Kauf · PDF-Download nach Zahlung. E-Mail-Bestätigung genügt für die Kontofreischaltung.</small></div><button type="button" data-buy="${esc(pid)}">Gesamtpaket kaufen</button>`;
   // nur Hefte mit einreichbarer Probe-Aufgabe in der Lernhilfe haben ein Bündel <heft>-mit-korrektur
   if(shop.products[KORREKTUR]&&shop.products[BUNDLE(pid)]){const k=document.createElement('div');k.className='shop-korrektur';k.style.cssText='margin-top:16px;padding-top:14px;border-top:1px solid rgba(21,58,54,.2)';const bundle=shop.products[BUNDLE(pid)];
    k.innerHTML=`<p style="margin:0"><b>Mit persönlicher Korrektur (Rückmeldung innerhalb von 24 Stunden, werktags): +${esc(price(shop.products[KORREKTUR].price))}</b></p><small>Eine Lehrerin korrigiert eine Schreibaufgabe oder Probe-Aufgabe aus dem Heft persönlich. Guthaben 12 Monate gültig. Du reichst deine Lösung in der <a href="/eltern-schueler/lernhilfe/">Lernhilfe</a> ein.</small>`+(capacity.available===false?`<p style="margin:12px 0 0"><b>${FULL}</b></p>`:(!ownsP(pid)&&current?.role!=='admin'?`<button type="button" data-buy="${esc(BUNDLE(pid))}">Heft + Korrektur · ${esc(price(bundle.price,bundle.currency))}</button>`:`<button type="button" data-buy="${KORREKTUR}">Korrektur kaufen · ${esc(price(shop.products[KORREKTUR].price))}</button>`));bar.append(k);}
   const productHead=theme.querySelector('.mappe-head__text');if(theme.classList.contains('product-detail')&&productHead){productHead.prepend(bar);const sample=productHead.querySelector('[data-sample]');if(sample)bar.append(sample);}else box.prepend(bar);
  });
 }
 document.addEventListener('click',e=>{const b=e.target.closest('[data-buy]');if(!b)return;e.preventDefault();openPurchase(b.dataset.buy,()=>location.reload());});
 document.addEventListener('toggle',()=>decorate(),true);
 let sdk=null;
 function loadSdk(){if(window.paypal)return Promise.resolve();if(sdk)return sdk;sdk=new Promise((ok,fail)=>{const s=document.createElement('script');s.src='https://www.paypal.com/sdk/js?client-id='+encodeURIComponent(shop.clientId)+'&currency=EUR&intent=capture&locale=de_DE&components=buttons&disable-funding=sepa,paylater';s.onload=ok;s.onerror=()=>fail(Error('PayPal konnte nicht geladen werden.'));document.head.append(s);});return sdk;}
 async function openPurchase(pid,done){
  await shopReady;const p=shop.products[pid];if(!p||!shop.enabled){showNotice('Der Kauf ist gerade nicht möglich.');return;}
  if(!token()){sessionStorage.setItem('materialinsel-return',location.pathname+location.hash);location.href='/konto/';return;}
  if(current&&current.status!=='approved'){showNotice('Bitte bestätige zuerst deine E-Mail-Adresse unter Mein Konto. Danach kannst du Mappen kaufen.');return;}
  const service=!!p.credits,hasFiles=!!(p.files&&p.files.length);
  if(service){try{capacity=await (await fetch(API+'/learning/capacity')).json();}catch(e){}if(capacity.available===false){korrekturStatus();showNotice(FULL);return;}}
  document.querySelector('#shop-dialog')?.remove();
  const d=document.createElement('dialog');d.id='shop-dialog';d.className='shop-dialog';
  d.innerHTML=`<form method="dialog" class="shop-close"><button aria-label="Schließen">×</button></form><p class="eyebrow">${service?(hasFiles?'HEFT + KORREKTUR KAUFEN':'KORREKTUR KAUFEN'):'MAPPE KAUFEN'}</p><h2>${esc(p.title)}</h2><p class="shop-total">${esc(price(p.price,p.currency))} <small>Endpreis</small></p><p class="shop-tax">Gemäß § 19 UStG wird keine Umsatzsteuer berechnet.</p><p>${service?(hasFiles?'Nach der Zahlung kannst du das Heft sofort herunterladen. ':'')+'Du erhältst ein Korrekturguthaben für eine Abgabe (eine Schreibaufgabe oder Probe-Aufgabe). Eine Lehrerin korrigiert deine Lösung persönlich – <strong>Rückmeldung innerhalb von 24 Stunden (werktags) nach deiner Abgabe</strong>. Das Guthaben ist 12 Monate gültig. Die Bestellbestätigung kommt per E-Mail.':'Nach der Zahlung sind alle Downloads dieser Mappe sofort und dauerhaft in deinem Konto freigeschaltet. Die Bestellbestätigung kommt per E-Mail.'}</p>${hasFiles?'<label class="shop-consent"><input type="checkbox" data-consent> Ich stimme ausdrücklich zu, dass die Materialinsel vor Ablauf der Widerrufsfrist mit der Bereitstellung der digitalen Inhalte beginnt. Mir ist bekannt, dass ich dadurch mein Widerrufsrecht verliere.</label>':''}${service?'<label class="shop-consent"><input type="checkbox" data-consent> Ich verlange ausdrücklich, dass die Materialinsel mit der Korrektur vor Ablauf der Widerrufsfrist beginnt, sobald ich eine Aufgabe einreiche. Mir ist bekannt, dass ich mein Widerrufsrecht verliere, wenn die Korrektur vollständig erbracht ist.</label>':''}<p class="shop-legal">Es gelten die <a href="/agb/" target="_blank">AGB</a> und die <a href="/agb/#widerruf" target="_blank">Widerrufsbelehrung</a>. Hinweise zu PayPal in der <a href="/konto/datenschutz.html" target="_blank">Datenschutzerklärung</a>.</p><div data-paypal class="shop-paypal"></div><p role="status" class="shop-status" data-status></p>`;
  document.body.append(d);d.showModal();
  const status=t=>d.querySelector('[data-status]').textContent=t;const consents=[...d.querySelectorAll('[data-consent]')],agreed=()=>consents.every(c=>c.checked);
  try{await loadSdk();}catch(e){status(e.message);return;}
  window.paypal.Buttons({style:{layout:'vertical',label:'buynow'},
   onInit:(_,actions)=>{actions.disable();consents.forEach(c=>c.onchange=()=>agreed()?actions.enable():actions.disable());},
   onClick:()=>{if(!agreed())status(consents.length>1?'Bitte zuerst beide Kästchen bestätigen.':'Bitte zuerst das Kästchen bestätigen.');},
   createOrder:async()=>{status('');return (await call('/paypal/order',{product:pid,...(hasFiles?{consent:true}:{}),...(service?{serviceConsent:true}:{})})).id;},
   onApprove:async data=>{status('Zahlung wird bestätigt …');try{const r=await call('/paypal/capture',{orderID:data.orderID});owned.add(pid);
    if(service&&!hasFiles){d.innerHTML=`<div class="shop-success"><div class="shop-success__icon" aria-hidden="true">✓</div><p class="eyebrow">KAUF ERFOLGREICH</p><h2>Dein Korrekturguthaben ist da!</h2><p>Reiche jetzt deine Lösung in der Lernhilfe ein. Deine Lehrerin schickt dir deine Rückmeldung innerhalb von 24 Stunden (werktags) nach deiner Abgabe. Das Guthaben ist 12 Monate gültig.</p><p class="shop-success__mail">${r.mailed===false?'Die Bestellbestätigung konnte gerade nicht verschickt werden. Wir schicken sie dir per E-Mail nach.':`Die Bestellbestätigung haben wir an <strong>${esc(current?current.email:'deine E-Mail-Adresse')}</strong> geschickt.`}</p><div class="shop-success__actions"><a href="/eltern-schueler/lernhilfe/" class="shop-success__primary">Zur Lernhilfe</a></div><button type="button" class="shop-success__close" data-success-close>Schließen</button></div>`;d.querySelector('[data-success-close]').onclick=()=>{d.close();d.remove();location.reload();};return;}const first=(p.files||[]).find(f=>document.querySelector(`[data-protected="${CSS.escape(f)}"]`));d.innerHTML=`<div class="shop-success"><div class="shop-success__icon" aria-hidden="true">✓</div><p class="eyebrow">KAUF ERFOLGREICH</p><h2>Vielen Dank für deinen Kauf!</h2><p><strong>${esc(p.title)}</strong> ist jetzt dauerhaft in deinem Konto freigeschaltet. Du kannst alle Dateien dieser Mappe sofort herunterladen.</p><p class="shop-success__mail">${r.mailed===false?'Die Bestellbestätigung konnte gerade nicht verschickt werden. Wir schicken sie dir per E-Mail nach.':`Die Bestellbestätigung haben wir an <strong>${esc(current?current.email:'deine E-Mail-Adresse')}</strong> geschickt. Schau bitte auch im Spam- oder Junk-Ordner nach.`}</p><div class="shop-success__actions"><button type="button" class="shop-success__primary" data-success-download>Jetzt herunterladen</button><a href="/konto/" class="shop-success__secondary">Meine Mappen ansehen</a></div><button type="button" class="shop-success__close" data-success-close>Schließen</button></div>`;d.querySelector('[data-success-close]').onclick=()=>{d.close();d.remove();location.reload();};d.querySelector('[data-success-download]').onclick=()=>{d.close();d.remove();decorate();const link=first&&document.querySelector(`[data-protected="${CSS.escape(first)}"]`);if(link){link.closest('details.theme-menu')?.setAttribute('open','');link.scrollIntoView({block:'center'});link.click();}else location.href='/konto/';};}catch(err){status(err.message);}},
   onCancel:()=>status('Zahlung abgebrochen. Es wurde nichts abgebucht.'),
   onError:err=>status((err&&err.message)||'Bei PayPal ist ein Fehler aufgetreten.')}).render(d.querySelector('[data-paypal]'));
 }
 function showNotice(text){let box=document.querySelector('#account-notice');if(!box){box=document.createElement('div');box.id='account-notice';box.className='account-notice';box.setAttribute('role','alert');document.body.append(box);}box.replaceChildren(document.createTextNode(text+' '));const a=document.createElement('a');a.href='/konto/';a.textContent='Zum Konto';box.append(a);const close=document.createElement('button');close.textContent='×';close.setAttribute('aria-label','Hinweis schließen');close.onclick=()=>box.remove();box.append(close);}
 const root=document.querySelector('[data-account]');if(!root)return;
 const adminPage=root.hasAttribute('data-admin-page');
 const msg=(s,error=false)=>{const box=root.querySelector('[data-message]');box.textContent=s;box.classList.toggle('is-error',error);};
 function bind(form,handler){form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;try{await handler(Object.fromEntries(new FormData(form)));}catch(err){msg(err.message,true);}finally{button.disabled=false;}};}
 const fragment=new URLSearchParams(location.hash.slice(1));const setup=fragment.get('setup'),reset=fragment.get('reset');
 if(setup||reset){history.replaceState(null,'',location.pathname);root.innerHTML=`<h2>${setup?'Deinen Verwaltungszugang einrichten':'Neues Passwort festlegen'}</h2><p>Dieser Link kann nur einmal verwendet werden.</p><form>${setup?'<label>E-Mail<input name="email" type="email" required autocomplete="email" maxlength="254"></label>':''}<label>Neues Passwort · mindestens 12 Zeichen<input name="password" type="password" minlength="12" maxlength="200" required autocomplete="new-password"></label><button type="submit">${setup?'Verwaltung aktivieren':'Passwort speichern'}</button></form><p role="status" data-message></p>`;bind(root.querySelector('form'),async d=>{await call(setup?'/setup':'/reset',{...d,token:setup||reset});root.innerHTML='<h2>Gespeichert</h2><p>Du kannst dich jetzt mit deiner E-Mail und deinem Passwort anmelden.</p><a href="/konto/">Zur Anmeldung</a>';});return;}
 if(new URLSearchParams(location.search).get('passwort')==='vergessen'){
  root.innerHTML='<h2>Passwort zurücksetzen</h2><p>Gib die E-Mail-Adresse deines Kontos ein. Wir senden dir einen Link, mit dem du ein neues Passwort festlegen kannst.</p><form data-forgot><label>E-Mail<input type="email" name="email" required maxlength="254" autocomplete="email"></label><button type="submit">Link per E-Mail anfordern</button></form><p role="status" aria-live="polite" data-message></p><p><a href="/konto/">Zurück zur Anmeldung</a></p>';
  bind(root.querySelector('form'),async d=>{const r=await call('/reset/request',d);msg(r.message);});return;
 }
 async function render(){
  await ready;
  if(current){
   if(adminPage&&current.role!=='admin'){root.innerHTML='<h2>Verwaltungszugang erforderlich</h2><p>Du bist mit einem Lehrkräftekonto angemeldet. Nur die Administration kann Accounts freischalten.</p><a href="/konto/">Zu deinem Konto</a>';return;}
   if(adminPage&&current.role==='admin'&&window.MaterialAdmin){await window.MaterialAdmin.mount(root,{call,current,logout:async()=>{try{await call('/logout',{});}catch{}sessionStorage.removeItem('materialinsel-session');location.reload();}});return;}
   if(current.status==='pending'&&current.role!=='admin'){
    root.innerHTML=`<p class="eyebrow">NUR NOCH EIN SCHRITT</p><h2>Bestätige deine E-Mail-Adresse</h2><p>Gib den sechsstelligen Code ein, den wir an <strong>${esc(current.email)}</strong> schicken. Danach ist dein Konto automatisch freigeschaltet.</p><form data-verify><label>Bestätigungscode<input name="code" type="text" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" minlength="6" maxlength="6" required placeholder="123456" aria-describedby="code-help"></label><p id="code-help" class="account-help">Der Code gilt 10 Minuten. Es zählt immer der zuletzt angeforderte Code. Nach fünf falschen Eingaben benötigst du einen neuen.</p><button type="submit">E-Mail bestätigen & Konto freischalten</button></form><p><button type="button" data-resend>Code senden / erneut senden</button></p><p role="status" aria-live="polite" data-message></p><p class="account-help">Keine E-Mail erhalten? Prüfe deinen Spamordner. Einen neuen Code kannst du nach 60 Sekunden anfordern.</p><p class="account-help">Kostenpflichtige Mappen kaufst du nach der Freischaltung einzeln. Falsche E-Mail-Adresse? <a href="mailto:shop@materialinsel.de">Kontakt aufnehmen</a>.</p><button type="button" data-logout>Abmelden</button>`;
    const notice=sessionStorage.getItem('materialinsel-verification-notice');
    if(notice){sessionStorage.removeItem('materialinsel-verification-notice');msg(notice);}
    bind(root.querySelector('[data-verify]'),async d=>{await call('/verify-email',d);const back=returnToMap();if(back)location.href=back;else location.reload();});
    root.querySelector('[data-resend]').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{const r=await call('/verify-email/request',{});msg(r.message);}catch(err){msg(err.message,true);}finally{b.disabled=false;}};
    root.querySelector('[data-logout]').onclick=async()=>{try{await call('/logout',{});}catch{}sessionStorage.removeItem('materialinsel-session');location.reload();};
    return;
   }
   root.innerHTML=`<h2>Hallo ${esc(current.name)}</h2><p class="account-status">${current.status==='approved'?'Konto freigeschaltet · Mappen können gekauft und gekaufte Dateien heruntergeladen werden':'E-Mail-Bestätigung ausstehend'}</p><p>${esc(current.email)} · ${esc(current.school)}</p><p><a href="${esc(/^\/(faecher|mappen|projekte|eltern-schueler)\//.test(sessionStorage.getItem('materialinsel-return')||'')?sessionStorage.getItem('materialinsel-return'):'/lehrkraefte/#mappen')}">Zu den Materialien →</a></p><button type="button" data-logout>Abmelden</button><p role="status" data-message></p>${current.role==='admin'?'<section class="account-admin"><p><a class="button" href="/admin.html">Adminübersicht & Statistik →</a></p><h2>Konten freischalten</h2><p>Name und Schule sind Selbstauskünfte. Neue Konten werden nach Bestätigung der E-Mail-Adresse automatisch freigeschaltet. Du kannst Konten weiterhin manuell freigeben oder sperren.</p><div data-users></div></section>':''}<p class="account-help"><a href="/konto/?passwort=vergessen">Passwort zurücksetzen</a> · Konto löschen lassen? <a href="mailto:shop@materialinsel.de">Materialinsel kontaktieren</a>.</p>`;
   shopReady.then(async()=>{if(!shop.enabled)return;const sec=document.createElement('section');sec.className='shop-owned';
    if(current.role==='admin'){try{const r=await call('/admin/purchases');sec.innerHTML='<h3>Verkäufe</h3>'+(r.purchases.length?'<ul>'+r.purchases.map(p=>`<li>${esc(new Date(p.created*1000).toLocaleDateString('de-DE'))} · ${esc(p.title)} · ${esc(p.name)} (${esc(p.email)}) · ${p.source==='paypal'?esc(price(p.amount,p.currency)):'manuell freigegeben'}</li>`).join('')+'</ul>':'<p>Noch keine Verkäufe.</p>')+((r.credits||[]).length?'<h3>Korrekturguthaben</h3><ul>'+r.credits.map(k=>`<li>${esc(new Date(k.created*1000).toLocaleDateString('de-DE'))} · ${esc(k.title)} · ${esc(k.name)} (${esc(k.email)}) · ${k.used?'eingelöst':(Date.now()/1000-k.created>365*86400?'abgelaufen':'offen')}${k.source==='paypal'?'':' · '+esc(k.source)}</li>`).join('')+'</ul>':'');}catch(e){return;}}
    else{const slug=t=>String(t).normalize('NFKD').replace(/[^\x00-\x7F]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60);const subj=t=>/Löcher|Lesetagebuch|ZP 10 Deutsch|Pyjama|Was wir dachten/i.test(t)?'deutsch':/philosoph|Wer bin ich|Naturwesen|Bauch|Welt vor/i.test(t)?'praktische-philosophie':'geschichte';const list=[...owned].map(pid=>shop.products[pid]&&[pid,shop.products[pid].title]).filter(Boolean);sec.innerHTML='<h3>Meine Mappen</h3>'+(list.length?'<ul class="owned-list">'+list.map(([pid,t])=>`<li><a href="${pid==='zweitzeugen-projekt-wfu'?'/projekte/wfu-zweitzeugen/':/^selbstlernheft-/.test(pid)?'/mappen/'+pid.replace(/-mit-korrektur$/,'')+'/':'/faecher/'+subj(t)+'/#'+slug(t)}">${esc(t)}</a> <span>· zum Herunterladen</span></li>`).join('')+'</ul>':'<p>Du hast noch keine Mappe gekauft. Auf den Fachseiten kannst du einzelne Mappen kaufen.</p>');}
    root.append(sec);});
   root.querySelector('[data-logout]').onclick=async()=>{try{await call('/logout',{});}catch{}sessionStorage.removeItem('materialinsel-session');location.reload();};
   if(current.role==='admin')await loadAdmin();return;
  }
  root.innerHTML='<div class="account-columns"><section><h2>Anmelden</h2><form data-login><label>E-Mail<input type="email" name="email" required autocomplete="username"></label><label>Passwort<input type="password" name="password" required autocomplete="current-password"></label><button type="submit">Anmelden</button></form><p class="account-help"><a href="/konto/?passwort=vergessen">Passwort vergessen?</a></p></section><section><h2>Konto anlegen</h2><p>Für Lehrkräfte, Eltern und Schüler. Bestätige deine E-Mail-Adresse mit einem Code und dein Konto wird automatisch freigeschaltet.</p><form data-register><label>Name<input name="name" required minlength="2" maxlength="120" autocomplete="name"></label><label>Schule / Bildungseinrichtung (Eltern: Schule deines Kindes)<input name="school" required minlength="2" maxlength="200" autocomplete="organization"></label><label>E-Mail<input type="email" name="email" required maxlength="254" autocomplete="email"></label><label>Passwort · mindestens 12 Zeichen<input type="password" name="password" minlength="12" maxlength="200" required autocomplete="new-password"></label><p class="account-help">Die Angaben werden für dein Konto und die Bestätigung deiner E-Mail-Adresse gespeichert. <a href="/konto/datenschutz.html">Datenschutzhinweise</a></p><button type="submit">Konto anlegen & Code erhalten</button></form></section></div><p role="status" aria-live="polite" data-message></p>';
  if(adminPage){root.querySelector('[data-register]').closest('section').remove();root.querySelector('h2').textContent='Als Administratorin anmelden';}
  bind(root.querySelector('[data-login]'),async d=>{const result=await call('/login',d);sessionStorage.setItem('materialinsel-session',result.token);const back=returnToMap();if(back&&!adminPage&&result.user?.status==='approved')location.href=back;else location.reload();});
  if(!adminPage)bind(root.querySelector('[data-register]'),async d=>{const r=await call('/register',d);if(r.token){sessionStorage.setItem('materialinsel-session',r.token);sessionStorage.setItem('materialinsel-verification-notice',r.message);location.reload();}else{msg(r.message);}});
 }
 async function loadAdmin(){const data=await call('/admin/users');const container=root.querySelector('[data-users]');
  const users=data.users.filter(u=>u.role!=='admin');
  const pending=users.filter(u=>u.status==='pending').length;
  container.innerHTML=`<p class="account-status">${pending} offene Anfrage${pending===1?'':'n'} · ${users.filter(u=>u.status==='approved').length} freigeschaltet · ${users.filter(u=>u.status==='blocked').length} gesperrt</p>` + (users.sort((a,b)=>({pending:0,approved:1,blocked:2}[a.status]-{pending:0,approved:1,blocked:2}[b.status])).map(u=>`<article class="account-person"><strong>${esc(u.name)}</strong><span>${esc(u.school)} · ${esc(u.email)}</span><small>${u.email_verified_at?'E-Mail bestätigt':'E-Mail nicht bestätigt'} · ${({pending:'Wartet auf E-Mail-Bestätigung',approved:'Freigeschaltet',blocked:'Gesperrt'})[u.status]}</small><div class="account-actions">${u.status!=='approved'?`<button data-id="${esc(u.id)}" data-status="approved">Freischalten</button>`:`<button data-id="${esc(u.id)}" data-status="blocked">Sperren</button>`}<button data-reset="${esc(u.id)}">Passwort-Link</button><button data-delete="${esc(u.id)}">Konto löschen</button></div></article>`).join('')||'<p>Es liegen noch keine Anfragen vor.</p>');
  container.onclick=async e=>{const b=e.target.closest('button');if(!b)return;b.disabled=true;try{
   if(b.dataset.status){await call('/admin/users/'+b.dataset.id,{status:b.dataset.status},'PATCH');await loadAdmin();msg('Kontostatus aktualisiert.');}
   if(b.dataset.reset){const d=await call('/admin/users/'+b.dataset.reset+'/reset',{});const url=location.origin+'/konto/#reset='+d.token;msg('Passwort-Link (24 Stunden gültig). Nur der betreffenden Person persönlich weitergeben: '+url);}
   if(b.dataset.delete&&confirm('Dieses Konto und seine Anmeldungen dauerhaft löschen?')){await call('/admin/users/'+b.dataset.delete,{},'DELETE');await loadAdmin();msg('Konto gelöscht.');}
  }catch(err){msg(err.message,true);}finally{b.disabled=false;}};
 }
 render().catch(e=>{root.innerHTML='<p role="alert">Der Kontobereich ist momentan nicht erreichbar. Bitte später erneut versuchen.</p>';});
})();
