(() => {
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>Number(n||0).toLocaleString('de-DE');
const date=s=>new Date(s).toLocaleDateString('de-DE');
window.MaterialAdmin={async mount(root,{call,current,logout}){
 let users=[],stats=null,sales=null,days=30,status='pending',query='',view='overview',metric='pageviews';
 root.innerHTML=`<div class="admin-shell"><aside class="admin-sidebar"><a class="admin-brand" href="/">Materialinsel<span>VERWALTUNG</span></a><nav aria-label="Verwaltung"><button data-view="overview" aria-current="page">Übersicht</button><button data-view="requests">Zugangsanträge <span data-pending>–</span></button><button data-view="accounts">Alle Konten</button><button data-view="sales">Verkäufe</button><button data-view="downloads">Downloads</button><button data-view="pages">Seiten & Besuche</button></nav><div class="admin-identity"><strong>${esc(current.name)}</strong><span>${esc(current.email)}</span><button data-logout>Abmelden</button></div></aside><div class="admin-workspace"><header class="admin-toolbar"><div><p class="eyebrow">MATERIALINSEL / ADMIN</p><h1 data-heading>Übersicht</h1></div><div class="admin-tools"><label>Zeitraum<select data-days><option value="7">Letzte 7 Tage</option><option value="30" selected>Letzte 30 Tage</option><option value="90">Letzte 90 Tage</option></select></label><button data-refresh>Aktualisieren</button><a href="/">Zur Website ↗</a></div></header><p data-message role="status" aria-live="polite"></p><div data-content><p>Statistik und Anfragen werden geladen …</p></div><p class="admin-footnote" data-updated></p></div></div>`;
 const content=root.querySelector('[data-content]'),message=root.querySelector('[data-message]');
 const tell=(text,error=false)=>{message.textContent=text;message.classList.toggle('is-error',error);};
 root.querySelector('[data-logout]').onclick=logout;
 function card(label,value,note){return `<article class="admin-metric"><span>${label}</span><strong>${num(value)}</strong><small>${note}</small></article>`;}
 function activity(){
 const labels={pageviews:'Seitenaufrufe',visitors:'Tagesbesucher',downloads:'Downloads / Klicks'};
 const timeline=stats.timeline.filter(d=>d.day>=String(stats.started).slice(0,10));
 if(!timeline.length)return '<section class="admin-panel"><h2>Besuche im Verlauf</h2><p>Noch keine Messwerte vorhanden.</p></section>';
 const max=Math.max(1,...timeline.map(d=>d[metric]||0)),today=timeline.at(-1),yesterday=timeline.at(-2),sum=timeline.reduce((a,d)=>a+(d[metric]||0),0),peak=timeline.reduce((a,d)=>d[metric]>a[metric]?d:a,timeline[0]);
 return `<section class="admin-panel"><div class="admin-panel-head"><div><h2>Besuche im Verlauf</h2><p class="admin-muted">${date(timeline[0].day)} bis ${date(today.day)} · ${timeline.length} erfasste Tage</p></div><label>Anzeige<select data-chart-metric>${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${metric===k?'selected':''}>${v}</option>`).join('')}</select></label></div>
 <div class="analytics-highlights"><div><span>Heute · noch laufend</span><strong>${num(today[metric])}</strong></div><div><span>Gestern</span><strong>${yesterday?num(yesterday[metric]):'–'}</strong></div><div><span>Durchschnitt pro erfasstem Tag</span><strong>${(sum/timeline.length).toLocaleString('de-DE',{maximumFractionDigits:1})}</strong></div><div><span>Stärkster Tag · ${date(peak.day)}</span><strong>${num(peak[metric])}</strong></div></div>
 <div class="analytics-scroll"><div class="analytics-chart" style="min-width:${Math.max(500,timeline.length*35)}px"><div class="analytics-scale"><span>${num(max)}</span><span>${num(Math.round(max/2))}</span><span>0</span></div><div class="analytics-bars">${timeline.map(d=>`<button class="analytics-day" data-day="${d.day}" aria-label="${date(d.day)}: ${num(d[metric])} ${labels[metric]}" title="${date(d.day)}: ${num(d.pageviews)} Aufrufe, ${num(d.visitors)} Tagesbesucher, ${num(d.downloads)} Downloads / Klicks"><span class="analytics-value">${num(d[metric])}</span><span class="analytics-column" style="height:${Math.max(d[metric]?3:0,(d[metric]||0)/max*190)}px"></span><span class="analytics-date">${d.day.slice(8)}.${d.day.slice(5,7)}.</span></button>`).join('')}</div></div></div>
 <p data-day-info class="analytics-detail" aria-live="polite">Wähle einen Tag im Diagramm für die genauen Werte.</p><details><summary>Alle Tageswerte als Tabelle</summary><div class="admin-table-wrap"><table><thead><tr><th>Datum</th><th>Aufrufe</th><th>Tagesbesucher</th><th>Downloads / Klicks</th></tr></thead><tbody>${timeline.slice().reverse().map(d=>`<tr><td>${date(d.day)}</td><td>${num(d.pageviews)}</td><td>${num(d.visitors)}</td><td>${num(d.downloads)}</td></tr>`).join('')}</tbody></table></div></details><p class="admin-muted">Erfassung seit ${date(stats.started)}. Frühere Tage sind ausgeblendet. Besucherwerte sind tägliche Schätzungen; dieselbe Person kann an mehreren Tagen erneut zählen.</p></section>`;
 }
 function table(items,type,limit=100){return !items.length?'<p class="admin-empty">Für diesen Zeitraum liegen noch keine Daten vor.</p>':`<div class="admin-table-wrap"><table><thead><tr><th>${type==='pages'?'Seite':'Material'}</th><th>${type==='pages'?'Aufrufe':'Downloads / Klicks'}</th></tr></thead><tbody>${items.slice(0,limit).map(x=>`<tr><td><strong>${esc(x.title)}</strong><small>${esc(x.key)}${type==='pages'?'':' · '+(x.kind==='teacher_download'?'Lehrkräfte · Datei ausgeliefert':'Schüler · Downloadlink angeklickt')}</small></td><td>${num(x.count)}</td></tr>`).join('')}</tbody></table></div>`;}
 const note='<p class="admin-muted">Tagesbesucher werden anhand einer täglich wechselnden Kennung geschätzt. Die Summe über mehrere Tage zählt wiederkehrende Personen mehrfach; gemeinsam genutzte Geräte oder Anschlüsse können zusammenfallen. Seitenbesuche werden nicht mit Konten verknüpft. Trackingblocker und Datenschutzeinstellungen können die Zählung verringern.</p>';

 const euro=c=>(Number(c||0)/100).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
 const salesIn=d=>!sales?[]:sales.purchases.filter(p=>p.source==='paypal'&&p.created*1000>=Date.now()-d*86400000);
 function salesView(){
  if(!sales)return '<p class="admin-empty">Verkaufsdaten werden geladen …</p>';
  const paid=sales.purchases.filter(p=>p.source==='paypal'),period=salesIn(days);
  const byProduct={};for(const p of paid){const b=byProduct[p.product_id]||(byProduct[p.product_id]={title:p.title,count:0,sum:0});b.count++;b.sum+=p.amount||0;}
  const prodRows=Object.entries(sales.products).map(([id,p])=>({id,title:p.title,price:p.price,...(byProduct[id]||{count:0,sum:0})})).sort((a,b)=>b.sum-a.sum||a.title.localeCompare(b.title));
  const approved=users.filter(u=>u.role!=='admin'&&u.status==='approved');
  return `<div class="admin-metrics">${card('Umsatz im Zeitraum',0,'')}${card('Verkäufe im Zeitraum',period.length,'Letzte '+days+' Tage')}${card('Verkäufe gesamt',paid.length,'Seit Start des Shops')}${card('Abgebrochene Bestellungen',sales.orders.length,'Bezahlvorgang begonnen, nicht abgeschlossen')}</div>
  <section class="admin-panel"><div class="admin-panel-head"><h2>Alle Verkäufe</h2><span>${sales.enabled?'Shop ist aktiv':'Shop ist ausgeschaltet'}</span></div>${sales.purchases.length?`<div class="admin-table-wrap"><table><thead><tr><th>Datum</th><th>Mappe</th><th>Käuferin / Käufer</th><th>Betrag</th><th></th></tr></thead><tbody>${sales.purchases.map(p=>`<tr><td>${new Date(p.created*1000).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'})}</td><td><strong>${esc(p.title)}</strong><small>${p.source==='paypal'?'PayPal · '+esc(p.reference):'Manuell freigeschaltet'+(p.reference?' · '+esc(p.reference):'')}</small></td><td><strong>${esc(p.name)}</strong><small>${esc(p.email)} · ${esc(p.school)}</small></td><td>${p.source==='paypal'?euro(p.amount):'–'}</td><td><button class="secondary danger" data-revoke="${p.id}" data-label="${esc(p.title+' für '+p.name)}">Zugang entziehen</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="admin-empty">Noch keine Verkäufe.</p>'}<p class="admin-muted">Rückerstattungen erledigst du in PayPal unter „Aktivitäten“. Danach hier „Zugang entziehen“ klicken, damit die Mappe nicht mehr heruntergeladen werden kann.</p></section>
  <section class="admin-panel"><h2>Verkäufe nach Mappe</h2><div class="admin-table-wrap"><table><thead><tr><th>Mappe</th><th>Preis</th><th>Verkäufe</th><th>Umsatz</th></tr></thead><tbody>${prodRows.map(r=>`<tr><td><strong>${esc(r.title)}</strong></td><td>${euro(r.price)}</td><td>${num(r.count)}</td><td>${euro(r.sum)}</td></tr>`).join('')}</tbody></table></div></section>
  <section class="admin-panel"><h2>Mappe manuell freischalten</h2><p class="admin-muted">Zum Beispiel bei Kauf auf Rechnung durch eine Schule oder als Geschenk. Es wird keine Zahlung ausgelöst.</p><form class="admin-filters" data-grant><label>Konto<select name="user" required><option value="">Konto wählen …</option>${approved.map(u=>`<option value="${esc(u.id)}">${esc(u.name)} · ${esc(u.email)}</option>`).join('')}</select></label><label>Mappe<select name="product" required><option value="">Mappe wählen …</option>${Object.entries(sales.products).map(([id,p])=>`<option value="${esc(id)}">${esc(p.title)}</option>`).join('')}</select></label><label>Notiz<input name="note" maxlength="200" placeholder="z. B. Rechnung Nr. …"></label><button type="submit">Freischalten</button></form></section>
  <section class="admin-panel"><h2>Abgebrochene Bestellungen</h2>${sales.orders.length?`<div class="admin-table-wrap"><table><thead><tr><th>Datum</th><th>Mappe</th><th>Konto</th><th>Status</th></tr></thead><tbody>${sales.orders.map(o=>`<tr><td>${new Date(o.created*1000).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'})}</td><td>${esc(o.title)}</td><td>${esc(o.name)}<small>${esc(o.email)}</small></td><td>${o.status==='failed'?'Zahlung nicht bestätigt':'Abgebrochen'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="admin-empty">Keine.</p>'}<p class="admin-muted">Bei abgebrochenen Bestellungen wurde nichts abgebucht.</p></section>`.replace(card('Umsatz im Zeitraum',0,''),`<article class="admin-metric"><span>Umsatz im Zeitraum</span><strong>${euro(period.reduce((a,p)=>a+(p.amount||0),0))}</strong><small>Letzte ${days} Tage · vor PayPal-Gebühren</small></article>`);
 }
 function accounts(){return `<section class="admin-panel"><div class="admin-panel-head"><h2>${view==='requests'?'Neue Zugangsanträge':'Konten verwalten'}</h2><span>${num(users.filter(u=>u.role!=='admin').length)} Lehrkräftekonten</span></div><p class="admin-muted">Name und Schule sind Selbstauskünfte. Neue Konten werden nach E-Mail-Bestätigung automatisch freigeschaltet. Manuelle Freigaben und Sperren bleiben möglich.</p><div class="admin-filters"><label>Suchen<input type="search" data-search placeholder="Name, E-Mail oder Schule" value="${esc(query)}"></label><label>Status<select data-status-filter>${[['pending','E-Mail-Bestätigung ausstehend'],['approved','Freigeschaltet'],['blocked','Gesperrt'],['all','Alle Konten']].map(([v,l])=>`<option value="${v}" ${v===status?'selected':''}>${l}</option>`).join('')}</select></label></div><div data-people></div></section>`;}
 function people(){const selected=users.filter(u=>u.role!=='admin'&&(status==='all'||u.status===status)&&[u.name,u.email,u.school].join(' ').toLocaleLowerCase('de').includes(query.toLocaleLowerCase('de')));root.querySelector('[data-people]').innerHTML=selected.length?selected.map(u=>`<article class="admin-person"><div><strong>${esc(u.name)}</strong><span>${esc(u.school)}</span><a href="mailto:${esc(u.email)}">${esc(u.email)}</a><small>Registriert am ${date(u.created*1000)} · ${u.email_verified_at?'E-Mail bestätigt am '+date(u.email_verified_at*1000):'E-Mail nicht bestätigt'}</small></div><div><span class="admin-badge ${u.status}">${({pending:'E-Mail-Bestätigung ausstehend',approved:'Freigeschaltet',blocked:'Gesperrt'})[u.status]}</span><div class="admin-actions">${u.status!=='approved'?`<button data-user="${esc(u.id)}" data-action="approved">Freischalten</button>`:`<button data-user="${esc(u.id)}" data-action="blocked">Sperren</button>`}<button class="secondary" data-user="${esc(u.id)}" data-action="reset">Passwort-Link</button><button class="secondary danger" data-user="${esc(u.id)}" data-action="delete">Löschen</button></div></div></article>`).join(''):'<p class="admin-empty">Keine passenden Anfragen oder Konten.</p>';}
 let downloadQuery='',downloadMode='summary',downloadSequence=0;
 function downloadPanel(){return `<section class="admin-panel" data-download-panel><h2>Wer hat was heruntergeladen?</h2><p class="admin-muted">Neue Abrufe geschützter Dateien mit Kontozuordnung. Frühere Downloads und freie Downloadklicks sind nur in der Materialstatistik darunter enthalten. Ein Abruf bestätigt nicht, dass die Datei vollständig gespeichert wurde.</p><form class="admin-filters" data-download-filters><label>Konto oder Material<input type="search" name="q" maxlength="200" placeholder="Name, E-Mail oder Materialtitel" value="${esc(downloadQuery)}"></label><label>Ansicht<select name="mode"><option value="summary" ${downloadMode==='summary'?'selected':''}>Nach Konto und Material</option><option value="events" ${downloadMode==='events'?'selected':''}>Einzelne Abrufe</option></select></label><button type="submit">Suchen</button></form><div data-download-results aria-live="polite"></div></section>`;}
 async function loadDownloads(page=1){
  const panel=root.querySelector('[data-download-panel]');if(!panel)return;
  const result=panel.querySelector('[data-download-results]'),seq=++downloadSequence;
  result.innerHTML='<p class="admin-muted">Downloadübersicht wird geladen …</p>';
  try{
   const d=await call('/admin/downloads?'+new URLSearchParams({days,page,mode:downloadMode,q:downloadQuery}));
   if(seq!==downloadSequence||!panel.isConnected)return;
   const stamp=t=>new Date(t*1000).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'medium',timeZone:'Europe/Berlin'});
   result.innerHTML=`<div class="download-totals"><span><strong>${num(d.totals.downloads)}</strong> Abrufe</span><span><strong>${num(d.totals.accounts)}</strong> ${d.totals.accounts===1?'Konto':'Konten'}</span><span><strong>${num(d.totals.materials)}</strong> ${d.totals.materials===1?'Material':'Materialien'}</span></div><p class="admin-muted">Kontozuordnung seit ${esc(new Date(d.started).toLocaleString('de-DE',{timeZone:'Europe/Berlin'}))}. Anzeige für die letzten ${num(d.days)} Tage. Uhrzeiten: Deutschland.</p>${d.items.length?`<div class="admin-table-wrap"><table><thead><tr><th>Konto</th><th>Material</th><th>${d.mode==='summary'?'Zuletzt abgerufen':'Abgerufen am'}</th><th>Anzahl</th></tr></thead><tbody>${d.items.map(x=>`<tr><td><strong>${esc(x.name)}</strong><small>${esc(x.email)}${x.role==='admin'?' · Verwaltung':''}</small></td><td><strong>${esc(x.title)}</strong><small>${esc(x.file_id)}</small></td><td>${stamp(x.created)}</td><td>${num(x.count)}</td></tr>`).join('')}</tbody></table></div><div class="download-pagination"><button class="secondary" data-download-page="${d.page-1}" ${d.page===1?'disabled':''}>Zurück</button><span>Seite ${num(d.page)} von ${num(d.pages)} · ${num(d.total)} Einträge</span><button class="secondary" data-download-page="${d.page+1}" ${d.page===d.pages?'disabled':''}>Weiter</button></div>`:'<p class="admin-empty">Noch keine passenden Abrufe mit Kontozuordnung. Ältere Downloads können nachträglich keinem Konto zugeordnet werden.</p>'}<p class="admin-muted">Nur für die Verwaltung sichtbar. Kontobezogene Abrufe werden höchstens 90 Tage angezeigt und bei der nächsten Erfassung oder Auswertung bereinigt. Do Not Track und Global Privacy Control werden berücksichtigt.</p>`;
   result.querySelectorAll('[data-download-page]').forEach(b=>b.onclick=()=>loadDownloads(Number(b.dataset.downloadPage)));
  }catch(e){if(seq===downloadSequence&&panel.isConnected)result.innerHTML=`<p class="is-error" role="alert">Die Kontozuordnung konnte nicht geladen werden: ${esc(e.message)}</p><button class="secondary" data-download-retry>Erneut versuchen</button>`;result.querySelector('[data-download-retry]')?.addEventListener('click',()=>loadDownloads(page));}
 }
 function render(){if(!stats)return;root.querySelector('[data-heading]').textContent=({overview:'Übersicht',requests:'Zugangsanträge',accounts:'Konten verwalten',sales:'Verkäufe',downloads:'Downloads',pages:'Seiten & Besuche'})[view];root.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});root.querySelector('[data-pending]').textContent=num(stats.accounts.pending);
 if(view==='overview')content.innerHTML=`<div class="admin-metrics">${card('Seitenaufrufe',stats.totals.pageviews,'Im gewählten Zeitraum')}${card('Tagesbesucher, summiert',stats.totals.visitors,'Geschätzte Nutzung pro Tag')}${card('Downloads / Klicks',stats.totals.downloads,'Schüler- und Lehrkräftematerial')}${card('Unbestätigte Konten',stats.accounts.pending,'Aktueller Stand · alle Zeiträume')}</div>${sales?`<section class="admin-callout"><div><h2>${euro(salesIn(days).reduce((a,p)=>a+(p.amount||0),0))} Umsatz in den letzten ${days} Tagen</h2><p>${num(salesIn(days).length)} Verkäufe · insgesamt ${euro(sales.purchases.reduce((a,p)=>a+(p.amount||0),0))}</p></div><button data-goto="sales">Verkäufe ansehen →</button></section>`:''}<section class="admin-callout"><div><h2>${num(stats.accounts.pending)} ${stats.accounts.pending===1?'Konto wartet':'Konten warten'} auf E-Mail-Bestätigung</h2><p>${num(stats.accounts.approved)} freigeschaltet · ${num(stats.accounts.blocked)} gesperrt</p></div><button data-goto="requests">Anträge prüfen →</button></section>${activity()}<div class="admin-two"><section class="admin-panel"><h2>Häufig heruntergeladen</h2>${table(stats.downloads,'downloads',5)}<button class="secondary" data-goto="downloads">Alle Downloads ansehen</button></section><section class="admin-panel"><h2>Beliebte Seiten</h2>${table(stats.pages,'pages',5)}<button class="secondary" data-goto="pages">Alle Seiten ansehen</button></section></div>${note}`;
 else if(view==='requests'||view==='accounts'){content.innerHTML=accounts();people();root.querySelector('[data-search]').oninput=e=>{query=e.target.value;people();};root.querySelector('[data-status-filter]').onchange=e=>{status=e.target.value;people();};}
 else if(view==='sales'){content.innerHTML=salesView();const f=root.querySelector('[data-grant]');if(f)f.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f));try{await call('/admin/purchases',d);tell('Mappe freigeschaltet.');await refresh();}catch(err){tell(err.message,true);}};}
 else if(view==='downloads')content.innerHTML=`${downloadPanel()}<section class="admin-panel"><h2>Materialien im gewählten Zeitraum</h2><p class="admin-muted">Bei freien PDFs zählen Klicks auf die Downloadlinks der Website. Direkt aufgerufene PDF-Adressen sind darin nicht enthalten. Geschützte Downloads werden nach erfolgreicher Berechtigungsprüfung am Server gezählt; abgebrochene Übertragungen lassen sich nicht sicher erkennen.</p>${table(stats.downloads,'downloads')}</section>`;
 else content.innerHTML=`<div class="admin-metrics">${card('Seitenaufrufe',stats.totals.pageviews,'Im gewählten Zeitraum')}${card('Tagesbesucher, summiert',stats.totals.visitors,'Keine eindeutige Personenzahl')}</div>${activity()}<section class="admin-panel"><h2>Aufgerufene Seiten</h2>${table(stats.pages,'pages')}</section>${note}`;
 if(view==='downloads'){
  const f=root.querySelector('[data-download-filters]');
  f.onsubmit=e=>{e.preventDefault();downloadQuery=f.elements.q.value.trim();downloadMode=f.elements.mode.value;loadDownloads();};
  f.elements.mode.onchange=()=>{downloadQuery=f.elements.q.value.trim();downloadMode=f.elements.mode.value;loadDownloads();};
  loadDownloads();
 }
 }
 let sequence=0;
 async function refresh(){const seq=++sequence;root.querySelector('[data-refresh]').disabled=true;try{const [s,u,p]=await Promise.all([call('/admin/stats?days='+days),call('/admin/users'),call('/admin/purchases').catch(()=>null)]);if(seq!==sequence)return;stats=s;users=u.users;sales=p;render();root.querySelector('[data-updated]').textContent='Zuletzt aktualisiert: '+new Date().toLocaleString('de-DE');}catch(e){if(seq===sequence)tell(e.message,true);}finally{if(seq===sequence)root.querySelector('[data-refresh]').disabled=false;}}
 root.querySelector('[data-refresh]').onclick=refresh;root.querySelector('[data-days]').onchange=e=>{days=Number(e.target.value);refresh();};
 root.addEventListener('change',e=>{if(e.target.matches('[data-chart-metric]')){metric=e.target.value;render();}});
 root.addEventListener('click',async e=>{const day=e.target.closest('[data-day]');if(day){const d=stats.timeline.find(x=>x.day===day.dataset.day);root.querySelector('[data-day-info]').textContent=date(d.day)+': '+num(d.pageviews)+' Seitenaufrufe · '+num(d.visitors)+' Tagesbesucher · '+num(d.downloads)+' Downloads / Klicks';return;}const rv=e.target.closest('[data-revoke]');if(rv){if(!confirm('Zugang entziehen: '+rv.dataset.label+'?'))return;rv.disabled=true;try{await call('/admin/purchases/'+rv.dataset.revoke,{},'DELETE');tell('Zugang entzogen.');await refresh();}catch(err){tell(err.message,true);rv.disabled=false;}return;}const nav=e.target.closest('[data-view],[data-goto]');if(nav){view=nav.dataset.view||nav.dataset.goto;query='';status=view==='accounts'?'all':'pending';render();return;}const b=e.target.closest('[data-action]');if(!b)return;const u=users.find(u=>u.id===b.dataset.user);if(!u)return;const action=b.dataset.action;
 if(action==='delete'&&!confirm('Konto von '+u.name+' und alle Anmeldungen dauerhaft löschen?'))return;
 b.disabled=true;try{if(action==='reset'){const d=await call('/admin/users/'+encodeURIComponent(u.id)+'/reset',{});tell('Passwort-Link für '+u.name+' (24 Stunden gültig). Persönlich weitergeben: '+location.origin+'/konto/#reset='+d.token);}else{await call('/admin/users/'+encodeURIComponent(u.id),action==='delete'?{}:{status:action},action==='delete'?'DELETE':'PATCH');tell(action==='delete'?'Konto gelöscht.':u.name+(action==='approved'?' wurde freigeschaltet.':' wurde gesperrt.'));await refresh();}}catch(err){tell(err.message,true);}finally{b.disabled=false;}});
 await refresh();
}};
})();
