(() => {
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>Number(n||0).toLocaleString('de-DE');
const date=s=>new Date(s).toLocaleDateString('de-DE');
window.MaterialAdmin={async mount(root,{call,current,logout}){
 let users=[],stats=null,days=30,status='pending',query='',view='overview';
 root.innerHTML=`<div class="admin-shell"><aside class="admin-sidebar"><a class="admin-brand" href="/">Materialinsel<span>VERWALTUNG</span></a><nav aria-label="Verwaltung"><button data-view="overview" aria-current="page">Übersicht</button><button data-view="requests">Zugangsanträge <span data-pending>–</span></button><button data-view="accounts">Alle Konten</button><button data-view="downloads">Downloads</button><button data-view="pages">Seiten & Besuche</button></nav><div class="admin-identity"><strong>${esc(current.name)}</strong><span>${esc(current.email)}</span><button data-logout>Abmelden</button></div></aside><div class="admin-workspace"><header class="admin-toolbar"><div><p class="eyebrow">MATERIALINSEL / ADMIN</p><h1 data-heading>Übersicht</h1></div><div class="admin-tools"><label>Zeitraum<select data-days><option value="7">Letzte 7 Tage</option><option value="30" selected>Letzte 30 Tage</option><option value="90">Letzte 90 Tage</option></select></label><button data-refresh>Aktualisieren</button><a href="/">Zur Website ↗</a></div></header><p data-message role="status" aria-live="polite"></p><div data-content><p>Statistik und Anfragen werden geladen …</p></div><p class="admin-footnote" data-updated></p></div></div>`;
 const content=root.querySelector('[data-content]'),message=root.querySelector('[data-message]');
 const tell=(text,error=false)=>{message.textContent=text;message.classList.toggle('is-error',error);};
 root.querySelector('[data-logout]').onclick=logout;
 function card(label,value,note){return `<article class="admin-metric"><span>${label}</span><strong>${num(value)}</strong><small>${note}</small></article>`;}
 function activity(){const max=Math.max(1,...stats.timeline.map(d=>d.pageviews));return `<section class="admin-panel"><h2>Seitenaufrufe im Verlauf</h2><div class="admin-chart" role="img" aria-label="${esc(stats.timeline.map(d=>date(d.day)+': '+d.pageviews+' Seitenaufrufe').join('; '))}">${stats.timeline.map(d=>`<div class="admin-bar-slot" title="${date(d.day)}: ${num(d.pageviews)} Seitenaufrufe"><span style="height:${d.pageviews?Math.max(2,d.pageviews/max*100):0}%"></span></div>`).join('')}</div><div class="admin-chart-axis"><span>${date(stats.timeline[0].day)}</span><span>${date(stats.timeline.at(-1).day)}</span></div><p class="admin-muted">Die Statistik läuft seit ${date(stats.started)}. Für die Zeit davor liegen keine Messwerte vor.</p></section>`;}
 function table(items,type,limit=100){return !items.length?'<p class="admin-empty">Für diesen Zeitraum liegen noch keine Daten vor.</p>':`<div class="admin-table-wrap"><table><thead><tr><th>${type==='pages'?'Seite':'Material'}</th><th>${type==='pages'?'Aufrufe':'Downloads / Klicks'}</th></tr></thead><tbody>${items.slice(0,limit).map(x=>`<tr><td><strong>${esc(x.title)}</strong><small>${esc(x.key)}${type==='pages'?'':' · '+(x.kind==='teacher_download'?'Lehrkräfte · Datei ausgeliefert':'Schüler · Downloadlink angeklickt')}</small></td><td>${num(x.count)}</td></tr>`).join('')}</tbody></table></div>`;}
 const note='<p class="admin-muted">Tagesbesucher werden anhand einer täglich wechselnden Kennung geschätzt. Die Summe über mehrere Tage zählt wiederkehrende Personen mehrfach; gemeinsam genutzte Geräte oder Anschlüsse können zusammenfallen. Keine Verknüpfung mit Konten. Trackingblocker und Datenschutzeinstellungen können die Zählung verringern.</p>';
 function accounts(){return `<section class="admin-panel"><div class="admin-panel-head"><h2>${view==='requests'?'Neue Zugangsanträge':'Konten verwalten'}</h2><span>${num(users.filter(u=>u.role!=='admin').length)} Lehrkräftekonten</span></div><p class="admin-muted">Name, Schule und E-Mail sind Selbstauskünfte. Die E-Mail-Adresse ist nicht automatisch verifiziert.</p><div class="admin-filters"><label>Suchen<input type="search" data-search placeholder="Name, E-Mail oder Schule" value="${esc(query)}"></label><label>Status<select data-status-filter>${[['pending','Wartet auf Freischaltung'],['approved','Freigeschaltet'],['blocked','Gesperrt'],['all','Alle Konten']].map(([v,l])=>`<option value="${v}" ${v===status?'selected':''}>${l}</option>`).join('')}</select></label></div><div data-people></div></section>`;}
 function people(){const selected=users.filter(u=>u.role!=='admin'&&(status==='all'||u.status===status)&&[u.name,u.email,u.school].join(' ').toLocaleLowerCase('de').includes(query.toLocaleLowerCase('de')));root.querySelector('[data-people]').innerHTML=selected.length?selected.map(u=>`<article class="admin-person"><div><strong>${esc(u.name)}</strong><span>${esc(u.school)}</span><a href="mailto:${esc(u.email)}">${esc(u.email)}</a><small>Beantragt am ${date(u.created*1000)}</small></div><div><span class="admin-badge ${u.status}">${({pending:'Wartet auf Freigabe',approved:'Freigeschaltet',blocked:'Gesperrt'})[u.status]}</span><div class="admin-actions">${u.status!=='approved'?`<button data-user="${esc(u.id)}" data-action="approved">Freischalten</button>`:`<button data-user="${esc(u.id)}" data-action="blocked">Sperren</button>`}<button class="secondary" data-user="${esc(u.id)}" data-action="reset">Passwort-Link</button><button class="secondary danger" data-user="${esc(u.id)}" data-action="delete">Löschen</button></div></div></article>`).join(''):'<p class="admin-empty">Keine passenden Anfragen oder Konten.</p>';}
 function render(){if(!stats)return;root.querySelector('[data-heading]').textContent=({overview:'Übersicht',requests:'Zugangsanträge',accounts:'Konten verwalten',downloads:'Downloads',pages:'Seiten & Besuche'})[view];root.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});root.querySelector('[data-pending]').textContent=num(stats.accounts.pending);
 if(view==='overview')content.innerHTML=`<div class="admin-metrics">${card('Seitenaufrufe',stats.totals.pageviews,'Im gewählten Zeitraum')}${card('Tagesbesucher, summiert',stats.totals.visitors,'Geschätzte Nutzung pro Tag')}${card('Downloads / Klicks',stats.totals.downloads,'Schüler- und Lehrkräftematerial')}${card('Offene Zugangsanträge',stats.accounts.pending,'Aktueller Stand · alle Zeiträume')}</div><section class="admin-callout"><div><h2>${num(stats.accounts.pending)} ${stats.accounts.pending===1?'Anfrage wartet':'Anfragen warten'} auf Prüfung</h2><p>${num(stats.accounts.approved)} freigeschaltet · ${num(stats.accounts.blocked)} gesperrt</p></div><button data-goto="requests">Anträge prüfen →</button></section>${activity()}<div class="admin-two"><section class="admin-panel"><h2>Häufig heruntergeladen</h2>${table(stats.downloads,'downloads',5)}<button class="secondary" data-goto="downloads">Alle Downloads ansehen</button></section><section class="admin-panel"><h2>Beliebte Seiten</h2>${table(stats.pages,'pages',5)}<button class="secondary" data-goto="pages">Alle Seiten ansehen</button></section></div>${note}`;
 else if(view==='requests'||view==='accounts'){content.innerHTML=accounts();people();root.querySelector('[data-search]').oninput=e=>{query=e.target.value;people();};root.querySelector('[data-status-filter]').onchange=e=>{status=e.target.value;people();};}
 else if(view==='downloads')content.innerHTML=`<section class="admin-panel"><h2>Materialien im gewählten Zeitraum</h2><p class="admin-muted">Bei freien PDFs zählen Klicks auf die Downloadlinks der Website. Direkt aufgerufene PDF-Adressen sind darin nicht enthalten. Geschützte Downloads werden nach erfolgreicher Berechtigungsprüfung am Server gezählt; abgebrochene Übertragungen lassen sich nicht sicher erkennen.</p>${table(stats.downloads,'downloads')}</section>`;
 else content.innerHTML=`<div class="admin-metrics">${card('Seitenaufrufe',stats.totals.pageviews,'Im gewählten Zeitraum')}${card('Tagesbesucher, summiert',stats.totals.visitors,'Keine eindeutige Personenzahl')}</div>${activity()}<section class="admin-panel"><h2>Aufgerufene Seiten</h2>${table(stats.pages,'pages')}</section>${note}`;
 }
 let sequence=0;
 async function refresh(){const seq=++sequence;root.querySelector('[data-refresh]').disabled=true;try{const [s,u]=await Promise.all([call('/admin/stats?days='+days),call('/admin/users')]);if(seq!==sequence)return;stats=s;users=u.users;render();root.querySelector('[data-updated]').textContent='Zuletzt aktualisiert: '+new Date().toLocaleString('de-DE');}catch(e){if(seq===sequence)tell(e.message,true);}finally{if(seq===sequence)root.querySelector('[data-refresh]').disabled=false;}}
 root.querySelector('[data-refresh]').onclick=refresh;root.querySelector('[data-days]').onchange=e=>{days=Number(e.target.value);refresh();};
 root.addEventListener('click',async e=>{const nav=e.target.closest('[data-view],[data-goto]');if(nav){view=nav.dataset.view||nav.dataset.goto;query='';status=view==='accounts'?'all':'pending';render();return;}const b=e.target.closest('[data-action]');if(!b)return;const u=users.find(u=>u.id===b.dataset.user);if(!u)return;const action=b.dataset.action;
 if(action==='delete'&&!confirm('Konto von '+u.name+' und alle Anmeldungen dauerhaft löschen?'))return;
 b.disabled=true;try{if(action==='reset'){const d=await call('/admin/users/'+encodeURIComponent(u.id)+'/reset',{});tell('Passwort-Link für '+u.name+' (24 Stunden gültig). Persönlich weitergeben: '+location.origin+'/konto/#reset='+d.token);}else{await call('/admin/users/'+encodeURIComponent(u.id),action==='delete'?{}:{status:action},action==='delete'?'DELETE':'PATCH');tell(action==='delete'?'Konto gelöscht.':u.name+(action==='approved'?' wurde freigeschaltet.':' wurde gesperrt.'));await refresh();}}catch(err){tell(err.message,true);}finally{b.disabled=false;}});
 await refresh();
}};
})();
