// Automatisch erzeugt von site/scripts/build-eltern-hefte.cjs (Stand der Heftliste: Oktober 2026) – nicht von Hand bearbeiten.
window.elternHefte = [
 {
  "id": "NRW_EESA_LV",
  "titel": "Leseverstehen Schritt für Schritt",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Erweiterter Erster Schulabschluss (EESA) · G-Kurs",
  "abschluss_kurz": "EESA",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil I · Leseverstehen",
  "seiten": 33,
  "preis": "5,90 €",
  "kurzbeschreibung": "Teil I der ZP 10 Deutsch (EESA, G-Kurs) in sechs kleinen Schritten üben: ankreuzen, zuordnen, Grafiken lesen, kurz erklären und Stellung nehmen. Mit Probe-Aufgabe und allen Lösungen.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-eesa-leseverstehen/"
 },
 {
  "id": "NRW_EESA_4A",
  "titel": "Einen Text analysieren",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Erweiterter Erster Schulabschluss (EESA) · G-Kurs",
  "abschluss_kurz": "EESA",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil II · Wahlaufgabe 1 (Typ 4a)",
  "seiten": 33,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft zur Wahlaufgabe 1 der ZP 10 Deutsch NRW (EESA, G-Kurs): eine Kurzgeschichte Schritt für Schritt analysieren – mit Übungen, Musterlösungen und Probe-Aufgabe.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-eesa-typ-4a-text-analysieren/"
 },
 {
  "id": "NRW_EESA_4B",
  "titel": "Texte vergleichen Schritt für Schritt",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Erweiterter Erster Schulabschluss (EESA) · G-Kurs",
  "abschluss_kurz": "EESA",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil II · Wahlaufgabe 2 · Typ 4b",
  "seiten": 35,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft für den G-Kurs: Materialien zusammenfassen, Meinungen in indirekter Rede wiedergeben, Positionen vergleichen und Stellung nehmen – mit Probe-Aufgabe, Raster und Lösungen.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-eesa-typ-4b-texte-vergleichen/"
 },
 {
  "id": "NRW_EESA_T2",
  "titel": "Informieren mit Materialien",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Erweiterter Erster Schulabschluss (EESA) · G-Kurs",
  "abschluss_kurz": "EESA",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Teil II · Wahlaufgabe 2 · Aufgabentyp 2",
  "seiten": 35,
  "preis": "5,90 €",
  "kurzbeschreibung": "Schritt für Schritt zum informierenden Text aus Materialien (Typ 2) auf EESA-Niveau: Aufgabe verstehen, Grafiken auswerten, eigenständig schreiben – mit Lösungen und Probe-Aufgabe.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-eesa-typ-2-informierender-text/"
 },
 {
  "id": "NRW_EESA_T3",
  "titel": "Stellung nehmen Schritt für Schritt",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Erweiterter Erster Schulabschluss (EESA) · G-Kurs",
  "abschluss_kurz": "EESA",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Typ 3 · Stellung nehmen",
  "seiten": 30,
  "preis": "5,90 €",
  "kurzbeschreibung": "Begründet Stellung nehmen für die ZP 10 Deutsch (EESA, G-Kurs): Wo die Meinung in der Prüfung gefragt ist und wie man sie mit Gründen und Textstellen stützt. Mit Lösungen und Probe-Aufgabe.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-eesa-typ-3-stellung-nehmen/"
 },
 {
  "id": "NRW_MSA_LV",
  "titel": "Leseverstehen Schritt für Schritt",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Mittlerer Schulabschluss (MSA) · E-Kurs",
  "abschluss_kurz": "MSA",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil I · Leseverstehen",
  "seiten": 34,
  "preis": "5,90 €",
  "kurzbeschreibung": "Teil I der ZP 10 Deutsch (MSA, E-Kurs) gezielt trainieren: Distraktoren durchschauen, Grafiken einordnen, im Textzusammenhang erläutern, Stellung nehmen. Mit Probe-Aufgabe und Lösungen.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-msa-leseverstehen/"
 },
 {
  "id": "NRW_MSA_4A",
  "titel": "Einen Text analysieren",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Mittlerer Schulabschluss (MSA) · E-Kurs",
  "abschluss_kurz": "MSA",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil II · Wahlaufgabe 1 (Typ 4a)",
  "seiten": 35,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft zur Wahlaufgabe 1 der ZP 10 Deutsch NRW (MSA, E-Kurs): literarische Texte analysieren und sich kritisch auseinandersetzen – mit Musterlösungen und Probe-Aufgabe.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-msa-typ-4a-text-analysieren/"
 },
 {
  "id": "NRW_MSA_4B",
  "titel": "Informationen vergleichen und bewerten",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Mittlerer Schulabschluss (MSA) · E-Kurs",
  "abschluss_kurz": "MSA",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil II · Wahlaufgabe 2 · Typ 4b",
  "seiten": 36,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft für den E-Kurs: Sachtext und Grafik auswerten, Positionen in indirekter Rede darstellen, unter einem Gesichtspunkt vergleichen und kritisch Stellung nehmen – mit Probe-Aufgabe und Lösungen.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-msa-typ-4b-texte-vergleichen/"
 },
 {
  "id": "NRW_MSA_T2",
  "titel": "Informieren mit Materialien",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Mittlerer Schulabschluss (MSA) · E-Kurs",
  "abschluss_kurz": "MSA",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Teil II · Wahlaufgabe 2 · Aufgabentyp 2",
  "seiten": 36,
  "preis": "5,90 €",
  "kurzbeschreibung": "Materialgestützt informieren auf MSA-Niveau: Materialien gezielt auswerten, Zusammenhänge erläutern, begründet schlussfolgern – sechs Schritte mit Lösungen und einer Probe-Aufgabe im Prüfungsformat.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-msa-typ-2-informierender-text/"
 },
 {
  "id": "NRW_MSA_T3",
  "titel": "Stellung nehmen Schritt für Schritt",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Mittlerer Schulabschluss (MSA) · E-Kurs",
  "abschluss_kurz": "MSA",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Typ 3 · Stellung nehmen",
  "seiten": 32,
  "preis": "5,90 €",
  "kurzbeschreibung": "Begründet Stellung nehmen für die ZP 10 Deutsch (MSA, E-Kurs): Argumente mit Textbelegen stützen, Gegenargumente abwägen und Schlussaufgaben sicher lösen. Mit Lösungen und Probe-Aufgabe.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-msa-typ-3-stellung-nehmen/"
 },
 {
  "id": "HE_HS_LESEN",
  "titel": "Lesen Schritt für Schritt",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Hauptschulabschluss · Bildungsgang Hauptschule, Klasse 9",
  "abschluss_kurz": "HS",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil I · Lesen",
  "seiten": 31,
  "preis": "5,90 €",
  "kurzbeschreibung": "Für Teil I Lesen der ZAA Deutsch Hessen (Hauptschulabschluss): Operatoren, Ankreuz- und Zitieraufgaben, Kurzantworten zu Prosa und Sachtext, mit Probe-Aufgabe (30 Punkte) und allen Lösungen.",
  "url": "/mappen/selbstlernheft-hessen-hauptschule-lesen/"
 },
 {
  "id": "HE_HS_TEXTPRODUKTION",
  "titel": "Textproduktion Schritt für Schritt",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Hauptschulabschluss · Klasse 9",
  "abschluss_kurz": "HS",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Teil II.A · Textproduktion (Wahlaufgabe)",
  "seiten": 35,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft zur Wahlaufgabe der ZAA Deutsch Hessen (Hauptschulabschluss): Erzählen, Berichten, Beschreiben, Argumentieren, Wörter zählen, Musterlösungen und Probe-Aufgabe mit Raster.",
  "url": "/mappen/selbstlernheft-hessen-hauptschule-textproduktion/"
 },
 {
  "id": "HE_HS_SPRACHRICHTIGKEIT",
  "titel": "Sprachliche Richtigkeit sicher üben",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Hauptschulabschluss · Bildungsgang Hauptschule, Klasse 9",
  "abschluss_kurz": "HS",
  "pruefungsjahr": 2027,
  "lernbereich": "Sprache & Ausdruck",
  "pruefungsteil": "Teil II.B · Sprachliche Richtigkeit",
  "seiten": 29,
  "preis": "5,90 €",
  "kurzbeschreibung": "Für Teil II.B der ZAA Deutsch: Großschreibung, Fehler berichtigen, Wörterbuch, Kommas, das/dass, Zeitformen und Fälle – Schritt für Schritt mit vielen kurzen Übungen, Lösungen und Probe-Aufgabe (15 P.).",
  "url": "/mappen/selbstlernheft-hessen-hauptschule-sprachliche-richtigkeit/"
 },
 {
  "id": "HE_HS_PROBEPRUEFUNG",
  "titel": "Probeprüfung ZAA Deutsch",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Hauptschulabschluss · Klasse 9",
  "abschluss_kurz": "HS",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Probeprüfung · alle Teile",
  "seiten": 32,
  "preis": "6,90 €",
  "kurzbeschreibung": "Eine vollständige Probeprüfung zur ZAA Deutsch (Hauptschulabschluss) mit zwei Aufgabensätzen, Zeitplan, Bewertungsraster und Musterlösungen – zum Üben an einem Vormittag zu Hause.",
  "url": "/mappen/selbstlernheft-hessen-hauptschule-probeprufung/"
 },
 {
  "id": "HE_RS_LESEN",
  "titel": "Lesen und Deuten Schritt für Schritt",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Realschulabschluss · Bildungsgang Realschule, Klasse 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil I · Lesen",
  "seiten": 33,
  "preis": "5,90 €",
  "kurzbeschreibung": "Für Teil I Lesen der ZAA Deutsch Hessen (Realschulabschluss): Operatoren, Sachtext, Kurzgeschichte und Gedicht mit sprachlichen Mitteln, dazu eine Probe-Aufgabe (40 Punkte) und alle Lösungen.",
  "url": "/mappen/selbstlernheft-hessen-realschule-lesen/"
 },
 {
  "id": "HE_RS_TEXTPRODUKTION",
  "titel": "Textproduktion Schritt für Schritt",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Realschulabschluss · Klasse 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Teil II.A · Textproduktion (Wahlaufgabe)",
  "seiten": 35,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft zur Wahlaufgabe der ZAA Deutsch Hessen (Realschulabschluss): vier Textarten, Wörter zählen, Gegenargumente und Stilebene, Musterlösungen und Probe-Aufgabe mit Raster.",
  "url": "/mappen/selbstlernheft-hessen-realschule-textproduktion/"
 },
 {
  "id": "HE_RS_SPRACHRICHTIGKEIT",
  "titel": "Sprachliche Richtigkeit sicher üben",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Realschulabschluss · Bildungsgang Realschule, Klasse 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Sprache & Ausdruck",
  "pruefungsteil": "Teil II.B · Sprachliche Richtigkeit",
  "seiten": 33,
  "preis": "5,90 €",
  "kurzbeschreibung": "Für Teil II.B der ZAA Deutsch: Rechtschreibung, Wörterbuch, Kommas, Satzverbindungen, Zeitformen, Fälle, Passiv und indirekte Rede – mit vielen kurzen Übungen, Lösungen und Probe-Aufgabe (20 P.).",
  "url": "/mappen/selbstlernheft-hessen-realschule-sprachliche-richtigkeit/"
 },
 {
  "id": "HE_RS_PROBEPRUEFUNG",
  "titel": "Probeprüfung ZAA Deutsch",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Realschulabschluss · Klasse 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Probeprüfung · alle Teile",
  "seiten": 34,
  "preis": "6,90 €",
  "kurzbeschreibung": "Eine vollständige Probeprüfung zur ZAA Deutsch (Realschulabschluss) mit Gedicht und Sachtext zur Wahl, Zeitplan, Bewertungsraster und Musterlösungen – für einen Übungsvormittag zu Hause.",
  "url": "/mappen/selbstlernheft-hessen-realschule-probeprufung/"
 }
];
