// Automatisch erzeugt von site/scripts/build-eltern-hefte.cjs (Stand der Heftliste: Oktober 2026) – nicht von Hand bearbeiten.
window.elternHefte = [
 {
  "id": "NRW_EESA_LV",
  "titel": "Leseverstehen Schritt für Schritt",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Erweiterter Erster Schulabschluss (EESA) · G-Kurs",
  "abschluss_kurz": "EESA",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil I · Leseverstehen",
  "seiten": 33,
  "preis": "5,90 €",
  "kurzbeschreibung": "Teil I der ZP 10 Deutsch (EESA, G-Kurs) in sechs kleinen Schritten üben: ankreuzen, zuordnen, Grafiken lesen, kurz erklären und Stellung nehmen. Mit Probe-Aufgabe und allen Lösungen.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-eesa-leseverstehen/"
 },
 {
  "id": "NRW_EESA_4A",
  "titel": "Einen Text analysieren",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Erweiterter Erster Schulabschluss (EESA) · G-Kurs",
  "abschluss_kurz": "EESA",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil II · Wahlaufgabe 1 (Typ 4a)",
  "seiten": 33,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft zur Wahlaufgabe 1 der ZP 10 Deutsch NRW (EESA, G-Kurs): eine Kurzgeschichte Schritt für Schritt analysieren – mit Übungen, Musterlösungen und Probe-Aufgabe.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-eesa-typ-4a-text-analysieren/"
 },
 {
  "id": "NRW_EESA_4B",
  "titel": "Texte vergleichen Schritt für Schritt",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Erweiterter Erster Schulabschluss (EESA) · G-Kurs",
  "abschluss_kurz": "EESA",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil II · Wahlaufgabe 2 · Typ 4b",
  "seiten": 35,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft für den G-Kurs: Materialien zusammenfassen, Meinungen in indirekter Rede wiedergeben, Positionen vergleichen und Stellung nehmen – mit Probe-Aufgabe, Raster und Lösungen.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-eesa-typ-4b-texte-vergleichen/"
 },
 {
  "id": "NRW_EESA_T2",
  "titel": "Informieren mit Materialien",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Erweiterter Erster Schulabschluss (EESA) · G-Kurs",
  "abschluss_kurz": "EESA",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Teil II · Wahlaufgabe 2 · Aufgabentyp 2",
  "seiten": 35,
  "preis": "5,90 €",
  "kurzbeschreibung": "Schritt für Schritt zum informierenden Text aus Materialien (Typ 2) auf EESA-Niveau: Aufgabe verstehen, Grafiken auswerten, eigenständig schreiben – mit Lösungen und Probe-Aufgabe.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-eesa-typ-2-informierender-text/"
 },
 {
  "id": "NRW_EESA_T3",
  "titel": "Stellung nehmen Schritt für Schritt",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Erweiterter Erster Schulabschluss (EESA) · G-Kurs",
  "abschluss_kurz": "EESA",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Typ 3 · Stellung nehmen",
  "seiten": 30,
  "preis": "5,90 €",
  "kurzbeschreibung": "Begründet Stellung nehmen für die ZP 10 Deutsch (EESA, G-Kurs): Wo die Meinung in der Prüfung gefragt ist und wie man sie mit Gründen und Textstellen stützt. Mit Lösungen und Probe-Aufgabe.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-eesa-typ-3-stellung-nehmen/"
 },
 {
  "id": "NRW_MSA_LV",
  "titel": "Leseverstehen Schritt für Schritt",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Mittlerer Schulabschluss (MSA) · E-Kurs",
  "abschluss_kurz": "MSA",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil I · Leseverstehen",
  "seiten": 34,
  "preis": "5,90 €",
  "kurzbeschreibung": "Teil I der ZP 10 Deutsch (MSA, E-Kurs) gezielt trainieren: Distraktoren durchschauen, Grafiken einordnen, im Textzusammenhang erläutern, Stellung nehmen. Mit Probe-Aufgabe und Lösungen.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-msa-leseverstehen/"
 },
 {
  "id": "NRW_MSA_4A",
  "titel": "Einen Text analysieren",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Mittlerer Schulabschluss (MSA) · E-Kurs",
  "abschluss_kurz": "MSA",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil II · Wahlaufgabe 1 (Typ 4a)",
  "seiten": 35,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft zur Wahlaufgabe 1 der ZP 10 Deutsch NRW (MSA, E-Kurs): literarische Texte analysieren und sich kritisch auseinandersetzen – mit Musterlösungen und Probe-Aufgabe.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-msa-typ-4a-text-analysieren/"
 },
 {
  "id": "NRW_MSA_4B",
  "titel": "Informationen vergleichen und bewerten",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Mittlerer Schulabschluss (MSA) · E-Kurs",
  "abschluss_kurz": "MSA",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil II · Wahlaufgabe 2 · Typ 4b",
  "seiten": 36,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft für den E-Kurs: Sachtext und Grafik auswerten, Positionen in indirekter Rede darstellen, unter einem Gesichtspunkt vergleichen und kritisch Stellung nehmen – mit Probe-Aufgabe und Lösungen.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-msa-typ-4b-texte-vergleichen/"
 },
 {
  "id": "NRW_MSA_T2",
  "titel": "Informieren mit Materialien",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Mittlerer Schulabschluss (MSA) · E-Kurs",
  "abschluss_kurz": "MSA",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Teil II · Wahlaufgabe 2 · Aufgabentyp 2",
  "seiten": 36,
  "preis": "5,90 €",
  "kurzbeschreibung": "Materialgestützt informieren auf MSA-Niveau: Materialien gezielt auswerten, Zusammenhänge erläutern, begründet schlussfolgern – sechs Schritte mit Lösungen und einer Probe-Aufgabe im Prüfungsformat.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-msa-typ-2-informierender-text/"
 },
 {
  "id": "NRW_MSA_T3",
  "titel": "Stellung nehmen Schritt für Schritt",
  "land": "Nordrhein-Westfalen",
  "land_kurz": "NRW",
  "abschluss": "Mittlerer Schulabschluss (MSA) · E-Kurs",
  "abschluss_kurz": "MSA",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Typ 3 · Stellung nehmen",
  "seiten": 32,
  "preis": "5,90 €",
  "kurzbeschreibung": "Begründet Stellung nehmen für die ZP 10 Deutsch (MSA, E-Kurs): Argumente mit Textbelegen stützen, Gegenargumente abwägen und Schlussaufgaben sicher lösen. Mit Lösungen und Probe-Aufgabe.",
  "url": "/mappen/selbstlernheft-zp-10-nrw-msa-typ-3-stellung-nehmen/"
 },
 {
  "id": "HE_HS_LESEN",
  "titel": "Lesen Schritt für Schritt",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Hauptschulabschluss · Bildungsgang Hauptschule, Klasse 9",
  "abschluss_kurz": "HS",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil I · Lesen",
  "seiten": 31,
  "preis": "5,90 €",
  "kurzbeschreibung": "Für Teil I Lesen der ZAA Deutsch Hessen (Hauptschulabschluss): Operatoren, Ankreuz- und Zitieraufgaben, Kurzantworten zu Prosa und Sachtext, mit Probe-Aufgabe (30 Punkte) und allen Lösungen.",
  "url": "/mappen/selbstlernheft-hessen-hauptschule-lesen/"
 },
 {
  "id": "HE_HS_TEXTPRODUKTION",
  "titel": "Textproduktion Schritt für Schritt",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Hauptschulabschluss · Klasse 9",
  "abschluss_kurz": "HS",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Teil II.A · Textproduktion (Wahlaufgabe)",
  "seiten": 35,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft zur Wahlaufgabe der ZAA Deutsch Hessen (Hauptschulabschluss): Erzählen, Berichten, Beschreiben, Argumentieren, Wörter zählen, Musterlösungen und Probe-Aufgabe mit Raster.",
  "url": "/mappen/selbstlernheft-hessen-hauptschule-textproduktion/"
 },
 {
  "id": "HE_HS_SPRACHRICHTIGKEIT",
  "titel": "Sprachliche Richtigkeit sicher üben",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Hauptschulabschluss · Bildungsgang Hauptschule, Klasse 9",
  "abschluss_kurz": "HS",
  "pruefungsjahr": 2027,
  "lernbereich": "Sprache & Ausdruck",
  "pruefungsteil": "Teil II.B · Sprachliche Richtigkeit",
  "seiten": 29,
  "preis": "5,90 €",
  "kurzbeschreibung": "Für Teil II.B der ZAA Deutsch: Großschreibung, Fehler berichtigen, Wörterbuch, Kommas, das/dass, Zeitformen und Fälle – Schritt für Schritt mit vielen kurzen Übungen, Lösungen und Probe-Aufgabe (15 P.).",
  "url": "/mappen/selbstlernheft-hessen-hauptschule-sprachliche-richtigkeit/"
 },
 {
  "id": "HE_HS_PROBEPRUEFUNG",
  "titel": "Probeprüfung ZAA Deutsch",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Hauptschulabschluss · Klasse 9",
  "abschluss_kurz": "HS",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Probeprüfung · alle Teile",
  "seiten": 32,
  "preis": "6,90 €",
  "kurzbeschreibung": "Eine vollständige Probeprüfung zur ZAA Deutsch (Hauptschulabschluss) mit zwei Aufgabensätzen, Zeitplan, Bewertungsraster und Musterlösungen – zum Üben an einem Vormittag zu Hause.",
  "url": "/mappen/selbstlernheft-hessen-hauptschule-probeprufung/"
 },
 {
  "id": "HE_RS_LESEN",
  "titel": "Lesen und Deuten Schritt für Schritt",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Realschulabschluss · Bildungsgang Realschule, Klasse 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil I · Lesen",
  "seiten": 33,
  "preis": "5,90 €",
  "kurzbeschreibung": "Für Teil I Lesen der ZAA Deutsch Hessen (Realschulabschluss): Operatoren, Sachtext, Kurzgeschichte und Gedicht mit sprachlichen Mitteln, dazu eine Probe-Aufgabe (40 Punkte) und alle Lösungen.",
  "url": "/mappen/selbstlernheft-hessen-realschule-lesen/"
 },
 {
  "id": "HE_RS_TEXTPRODUKTION",
  "titel": "Textproduktion Schritt für Schritt",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Realschulabschluss · Klasse 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Teil II.A · Textproduktion (Wahlaufgabe)",
  "seiten": 35,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft zur Wahlaufgabe der ZAA Deutsch Hessen (Realschulabschluss): vier Textarten, Wörter zählen, Gegenargumente und Stilebene, Musterlösungen und Probe-Aufgabe mit Raster.",
  "url": "/mappen/selbstlernheft-hessen-realschule-textproduktion/"
 },
 {
  "id": "HE_RS_SPRACHRICHTIGKEIT",
  "titel": "Sprachliche Richtigkeit sicher üben",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Realschulabschluss · Bildungsgang Realschule, Klasse 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Sprache & Ausdruck",
  "pruefungsteil": "Teil II.B · Sprachliche Richtigkeit",
  "seiten": 33,
  "preis": "5,90 €",
  "kurzbeschreibung": "Für Teil II.B der ZAA Deutsch: Rechtschreibung, Wörterbuch, Kommas, Satzverbindungen, Zeitformen, Fälle, Passiv und indirekte Rede – mit vielen kurzen Übungen, Lösungen und Probe-Aufgabe (20 P.).",
  "url": "/mappen/selbstlernheft-hessen-realschule-sprachliche-richtigkeit/"
 },
 {
  "id": "HE_RS_PROBEPRUEFUNG",
  "titel": "Probeprüfung ZAA Deutsch",
  "land": "Hessen",
  "land_kurz": "HE",
  "abschluss": "Realschulabschluss · Klasse 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Probeprüfung · alle Teile",
  "seiten": 34,
  "preis": "6,90 €",
  "kurzbeschreibung": "Eine vollständige Probeprüfung zur ZAA Deutsch (Realschulabschluss) mit Gedicht und Sachtext zur Wahl, Zeitplan, Bewertungsraster und Musterlösungen – für einen Übungsvormittag zu Hause.",
  "url": "/mappen/selbstlernheft-hessen-realschule-probeprufung/"
 },
 {
  "id": "BY_QUALI_HOEREN",
  "titel": "Zuhören Schritt für Schritt",
  "land": "Bayern",
  "land_kurz": "BY",
  "abschluss": "Qualifizierender Abschluss der Mittelschule (Quali) · Klasse 9",
  "abschluss_kurz": "QUALI",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil A · Zuhören",
  "seiten": 32,
  "preis": "5,90 €",
  "kurzbeschreibung": "Teil A des Quali Deutsch Schritt für Schritt üben: vor dem Hören planen, Zahlen und Namen heraushören, Gespräche genau verstehen, Notizen machen, Aufgabenformate und Fallen kennen. Alle Hörtexte stehen als Vorlesetexte im Heft, dazu eine Probe-Aufgabe (12 P.) mit Lösungen.",
  "url": "/mappen/selbstlernheft-bayern-quali-zuhoren/"
 },
 {
  "id": "BY_QUALI_LESEN",
  "titel": "Lesen Schritt für Schritt",
  "land": "Bayern",
  "land_kurz": "BY",
  "abschluss": "Qualifizierender Abschluss der Mittelschule (Quali) · Klasse 9",
  "abschluss_kurz": "QUALI",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Teil C · Lesen",
  "seiten": 36,
  "preis": "5,90 €",
  "kurzbeschreibung": "Für Teil C der Quali-Prüfung Deutsch: Lesestrategien, Sachtexte, literarische Texte und Textsorten, sprachliche Bilder, Zitieren, Grafiken und innerer Monolog – Schritt für Schritt mit Lösungen und einer Probe-Aufgabe (24 P.).",
  "url": "/mappen/selbstlernheft-bayern-quali-lesen/"
 },
 {
  "id": "BY_QUALI_SCHREIBEN",
  "titel": "Schreiben Schritt für Schritt",
  "land": "Bayern",
  "land_kurz": "BY",
  "abschluss": "Qualifizierender Abschluss der Mittelschule (Quali) · Klasse 9",
  "abschluss_kurz": "QUALI",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Teil D · Schreiben",
  "seiten": 34,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft zu Teil D Schreiben im Quali Deutsch Bayern: Schreibplan, argumentierendes, informierendes und narratives Schreiben, kleine Schreibaufgaben, Überarbeiten mit Checkliste, ausformulierte Mustertexte und Probe-Aufgabe mit zwei Aufgabengruppen und Raster.",
  "url": "/mappen/selbstlernheft-bayern-quali-schreiben/"
 },
 {
  "id": "BY_QUALI_SPRACHGEBRAUCH",
  "titel": "Sprachbetrachtung und Rechtschreiben",
  "land": "Bayern",
  "land_kurz": "BY",
  "abschluss": "Qualifizierender Abschluss der Mittelschule (Quali) · Klasse 9",
  "abschluss_kurz": "QUALI",
  "pruefungsjahr": 2027,
  "lernbereich": "Sprache & Ausdruck",
  "pruefungsteil": "Teil B · Sprachgebrauch",
  "seiten": 36,
  "preis": "5,90 €",
  "kurzbeschreibung": "Für Teil B der Quali-Prüfung Deutsch in Bayern: Wortarten, Satzglieder, Sätze und Satzzeichen, Zeitformen und Passiv, Wortschatz, Rechtschreibstrategien begründen, Groß- und Kleinschreibung und Silbentrennung – Schritt für Schritt mit Lösungen und Probe-Aufgabe (12 P.).",
  "url": "/mappen/selbstlernheft-bayern-quali-sprachgebrauch/"
 },
 {
  "id": "BY_QUALI_PROBEPRUEFUNG",
  "titel": "Probeprüfung Quali Deutsch",
  "land": "Bayern",
  "land_kurz": "BY",
  "abschluss": "Qualifizierender Abschluss der Mittelschule (Quali) · Klasse 9",
  "abschluss_kurz": "QUALI",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Probeprüfung · alle Teile",
  "seiten": 36,
  "preis": "6,90 €",
  "kurzbeschreibung": "Eine vollständige Probeprüfung zum Quali Deutsch mit allen vier Teilen A bis D zum Rahmenthema „Zeit“ – mit Vorlesetexten für den Hörteil, Zeitplan, Bewertungsraster und Musterlösungen für einen Probe-Vormittag zu Hause.",
  "url": "/mappen/selbstlernheft-bayern-quali-probeprufung/"
 },
 {
  "id": "BY_RS_T1",
  "titel": "Materialgestützt argumentieren",
  "land": "Bayern",
  "land_kurz": "BY",
  "abschluss": "Realschulabschluss · Klasse 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Thema I · Materialgestütztes Argumentieren",
  "seiten": 36,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft zu Thema I der Abschlussprüfung Deutsch an der bayerischen Realschule: Themenfrage erschließen, Texte und Grafiken auswerten, eine gesonderte Gliederung anlegen und Argumente mit Materialbelegen ausbauen. Mit Lösungen, Mustergliederung und Probe-Aufgabe mit Bewertungsraster.",
  "url": "/mappen/selbstlernheft-bayern-realschule-thema-i-argumentieren/"
 },
 {
  "id": "BY_RS_T2",
  "titel": "Einen Sachtext erschließen",
  "land": "Bayern",
  "land_kurz": "BY",
  "abschluss": "Realschulabschluss · Klasse 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Thema II · Pragmatischen Text erschließen",
  "seiten": 36,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft für Thema II der Abschlussprüfung Deutsch an der bayerischen Realschule: journalistische Texte strukturiert zusammenfassen, Sprache und Textsorte untersuchen, Stellung nehmen und kreativ schreiben – mit Probe-Aufgabe, Raster und Musterlösung.",
  "url": "/mappen/selbstlernheft-bayern-realschule-thema-ii-sachtext/"
 },
 {
  "id": "BY_RS_T3",
  "titel": "Einen literarischen Text erschließen",
  "land": "Bayern",
  "land_kurz": "BY",
  "abschluss": "Realschulabschluss · Klasse 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Thema III · Literarischen Text erschließen",
  "seiten": 36,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft zu Thema III der Abschlussprüfung Deutsch an der bayerischen Realschule: einen literarischen Text in fünf Aufgaben erschließen, von der Inhaltszusammenfassung bis zum kreativen Schreibauftrag – mit Texten von Stefan Zweig und Ödön von Horváth, Musterlösungen und Probe-Aufgabe.",
  "url": "/mappen/selbstlernheft-bayern-realschule-thema-iii-literatur/"
 },
 {
  "id": "BY_RS_PROBEPRUEFUNG",
  "titel": "Probeprüfung Deutsch Realschule",
  "land": "Bayern",
  "land_kurz": "BY",
  "abschluss": "Realschulabschluss · Klasse 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Probeprüfung · Themen I–III",
  "seiten": 34,
  "preis": "6,90 €",
  "kurzbeschreibung": "Eine vollständige Probeprüfung zur Abschlussprüfung Deutsch an der bayerischen Realschule mit allen drei Themen zur Wahl, Entscheidungshilfe, Zeitplan, Bewertungsrastern und Musterlösungen – für einen Übungsvormittag zu Hause.",
  "url": "/mappen/selbstlernheft-bayern-realschule-probeprufung/"
 },
 {
  "id": "NI_HS9_HOEREN",
  "titel": "Hörverstehen Schritt für Schritt",
  "land": "Niedersachsen",
  "land_kurz": "NI",
  "abschluss": "Hauptschulabschluss · Schuljahrgang 9",
  "abschluss_kurz": "HS9",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Hauptteil 1 · Hörverstehen",
  "seiten": 33,
  "preis": "5,90 €",
  "kurzbeschreibung": "Hauptteil 1 der Abschlussprüfung Deutsch (Hauptschulabschluss, Jahrgang 9) zu Hause üben: Aufgaben vorher lesen, beim zweiten Hören Stichworte notieren, Aufgaben sicher lösen – mit sieben Hörtexten zum Vorlesen, Probe-Aufgabe und allen Lösungen.",
  "url": "/mappen/selbstlernheft-niedersachsen-hs-9-horverstehen/"
 },
 {
  "id": "NI_HS9_LESEN",
  "titel": "Lesen und Sprache Schritt für Schritt",
  "land": "Niedersachsen",
  "land_kurz": "NI",
  "abschluss": "Hauptschulabschluss · Schuljahrgang 9",
  "abschluss_kurz": "HS9",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Hauptteil 2 und Wahlteil · Lesen und Sprachgebrauch",
  "seiten": 34,
  "preis": "5,90 €",
  "kurzbeschreibung": "Für Hauptteil 2 und den Wahlteil der Abschlussprüfung Deutsch Niedersachsen (Hauptschulabschluss, Jahrgang 9): Lesestrategien, Sachtexte, Grafiken, Kurzgeschichte und Ballade, Grammatik und Rechtschreibung, mit Probe-Aufgabe (20 Punkte) und allen Lösungen.",
  "url": "/mappen/selbstlernheft-niedersachsen-hs-9-lesen-und-sprache/"
 },
 {
  "id": "NI_HS9_SCHREIBEN",
  "titel": "Eigene Texte Schritt für Schritt",
  "land": "Niedersachsen",
  "land_kurz": "NI",
  "abschluss": "Hauptschulabschluss · Schuljahrgang 9",
  "abschluss_kurz": "HS9",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Wahlteil · Eigenen Text schreiben",
  "seiten": 36,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft zum eigenen Text im Wahlteil der Abschlussprüfung Deutsch Niedersachsen (Hauptschulabschluss, Schuljahrgang 9): Aufgaben verstehen und planen, innerer Monolog, Brief, Stellungnahme, informierende und appellierende Texte, Überarbeiten, Probe-Aufgabe mit Musterlösung.",
  "url": "/mappen/selbstlernheft-niedersachsen-hs-9-schreiben/"
 },
 {
  "id": "NI_HS9_PROBEPRUEFUNG",
  "titel": "Probeprüfung Deutsch · Jahrgang 9",
  "land": "Niedersachsen",
  "land_kurz": "NI",
  "abschluss": "Hauptschulabschluss · Schuljahrgang 9",
  "abschluss_kurz": "HS9",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Probeprüfung · alle Teile",
  "seiten": 34,
  "preis": "6,90 €",
  "kurzbeschreibung": "Eine vollständige Probeprüfung Deutsch für den Hauptschulabschluss nach Schuljahrgang 9 in Niedersachsen mit Hörtext zum Vorlesen, zwei Wahlteilen, Zeitplan, Bewertungsraster und Musterlösungen.",
  "url": "/mappen/selbstlernheft-niedersachsen-hs-9-probeprufung/"
 },
 {
  "id": "NI_HS10_HOEREN",
  "titel": "Hörverstehen Schritt für Schritt",
  "land": "Niedersachsen",
  "land_kurz": "NI",
  "abschluss": "Sekundarabschluss I – Hauptschulabschluss · Schuljahrgang 10",
  "abschluss_kurz": "HS10",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Hauptteil 1 · Hörverstehen",
  "seiten": 33,
  "preis": "5,90 €",
  "kurzbeschreibung": "Hauptteil 1 der Abschlussprüfung Deutsch (Sekundarabschluss I – Hauptschulabschluss, Jahrgang 10) zu Hause üben: Hörstrategien, Mitschreiben mit System, geschlossene und offene Aufgaben, Meinung und Absicht von Sprechern – mit sieben Hörtexten zum Vorlesen, Probe-Aufgabe und allen Lösungen.",
  "url": "/mappen/selbstlernheft-niedersachsen-hs-10-horverstehen/"
 },
 {
  "id": "NI_HS10_LESEN",
  "titel": "Texte verstehen, Sprache sicher nutzen",
  "land": "Niedersachsen",
  "land_kurz": "NI",
  "abschluss": "Sekundarabschluss I – Hauptschulabschluss · Schuljahrgang 10",
  "abschluss_kurz": "HS10",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Hauptteil 2 und Wahlteil · Lesen und Sprachgebrauch",
  "seiten": 35,
  "preis": "5,90 €",
  "kurzbeschreibung": "Für Hauptteil 2 und den Wahlteil der Abschlussprüfung Deutsch Niedersachsen (Hauptschulabschluss, Jahrgang 10): Sachtexte und Kommentare, Tabellen und Karikaturen, Hebels „Kannitverstan“ und Goethes „Zauberlehrling“, Grammatik und Rechtschreibung, mit Probe-Aufgabe (28 Punkte) und allen Lösungen.",
  "url": "/mappen/selbstlernheft-niedersachsen-hs-10-lesen-und-sprache/"
 },
 {
  "id": "NI_HS10_SCHREIBEN",
  "titel": "Eigene Texte Schritt für Schritt",
  "land": "Niedersachsen",
  "land_kurz": "NI",
  "abschluss": "Sekundarabschluss I – Hauptschulabschluss · Schuljahrgang 10",
  "abschluss_kurz": "HS10",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Wahlteil · Eigenen Text schreiben",
  "seiten": 35,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft zum eigenen Text im Wahlteil der Abschlussprüfung Deutsch Niedersachsen (Hauptschulabschluss, Schuljahrgang 10): Aufgaben verstehen und planen, innerer Monolog, Brief, Argumentieren, informierend-appellierende Texte, Überarbeiten, Probe-Aufgabe mit Musterlösung.",
  "url": "/mappen/selbstlernheft-niedersachsen-hs-10-schreiben/"
 },
 {
  "id": "NI_HS10_PROBEPRUEFUNG",
  "titel": "Probeprüfung Deutsch · Jahrgang 10",
  "land": "Niedersachsen",
  "land_kurz": "NI",
  "abschluss": "Sekundarabschluss I – Hauptschulabschluss · Schuljahrgang 10",
  "abschluss_kurz": "HS10",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Probeprüfung · alle Teile",
  "seiten": 36,
  "preis": "6,90 €",
  "kurzbeschreibung": "Eine vollständige Probeprüfung Deutsch für den Hauptschulabschluss nach Schuljahrgang 10 in Niedersachsen mit Hörtext zum Vorlesen, zwei Wahlteilen, Zeitplan für 180 Minuten, Bewertungsraster und Musterlösungen.",
  "url": "/mappen/selbstlernheft-niedersachsen-hs-10-probeprufung/"
 },
 {
  "id": "NI_RS_HOEREN",
  "titel": "Hörverstehen Schritt für Schritt",
  "land": "Niedersachsen",
  "land_kurz": "NI",
  "abschluss": "Sekundarabschluss I – Realschulabschluss · Schuljahrgang 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Hauptteil 1 · Hörverstehen",
  "seiten": 36,
  "preis": "5,90 €",
  "kurzbeschreibung": "Für Hauptteil 1 der Abschlussprüfung Deutsch Niedersachsen (Realschulabschluss): Ablauf, Hörstrategien, Notiztechnik, Aufgabenformate, Fakt und Meinung, sieben Hörtexte zum Vorlesen und eine Probe-Aufgabe mit 12 Punkten.",
  "url": "/mappen/selbstlernheft-niedersachsen-realschule-horverstehen/"
 },
 {
  "id": "NI_RS_LESEN",
  "titel": "Texte untersuchen, Sprache betrachten",
  "land": "Niedersachsen",
  "land_kurz": "NI",
  "abschluss": "Sekundarabschluss I – Realschulabschluss · Schuljahrgang 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Hauptteil 2 und Wahlteil · Lesen und Sprachgebrauch",
  "seiten": 36,
  "preis": "5,90 €",
  "kurzbeschreibung": "Für Hauptteil 2 und den Wahlteil der Abschlussprüfung Deutsch Niedersachsen (Realschulabschluss): Lesestrategien, Zeitungstexte, Grafiken und Karikaturen, Erzählung und Gedicht, Sprachgebrauch und Rechtschreibung, dazu eine Probe-Aufgabe (28 Punkte) mit allen Lösungen.",
  "url": "/mappen/selbstlernheft-niedersachsen-realschule-lesen-und-sprache/"
 },
 {
  "id": "NI_RS_SCHREIBEN",
  "titel": "Eigene Texte Schritt für Schritt",
  "land": "Niedersachsen",
  "land_kurz": "NI",
  "abschluss": "Sekundarabschluss I – Realschulabschluss · Schuljahrgang 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Schreiben & Überarbeiten",
  "pruefungsteil": "Wahlteil · Eigenen Text schreiben",
  "seiten": 36,
  "preis": "5,90 €",
  "kurzbeschreibung": "Selbstlernheft zum eigenen Text im Wahlteil der Abschlussprüfung Deutsch Niedersachsen (Realschulabschluss) mit Schwerpunkt auf informierend-appellierenden Texten, dazu Argumentieren, Textuntersuchung, Überarbeiten, Musterlösungen und eine Probe-Aufgabe mit Raster.",
  "url": "/mappen/selbstlernheft-niedersachsen-realschule-schreiben/"
 },
 {
  "id": "NI_RS_PROBEPRUEFUNG",
  "titel": "Probeprüfung Deutsch",
  "land": "Niedersachsen",
  "land_kurz": "NI",
  "abschluss": "Sekundarabschluss I – Realschulabschluss · Schuljahrgang 10",
  "abschluss_kurz": "RS",
  "pruefungsjahr": 2027,
  "lernbereich": "Lesen & Verstehen",
  "pruefungsteil": "Probeprüfung · alle Teile",
  "seiten": 35,
  "preis": "6,90 €",
  "kurzbeschreibung": "Eine vollständige Probeprüfung zur Abschlussprüfung Deutsch (Realschulabschluss Niedersachsen) mit Hörverstehen, Hauptteil 2, Gedicht und Kommentar zur Wahl, Zeitplan, Bewertungsraster und Musterlösungen – für einen Übungsvormittag zu Hause.",
  "url": "/mappen/selbstlernheft-niedersachsen-realschule-probeprufung/"
 }
];
