(()=>{'use strict';
const API='https://api-production-c1a79.up.railway.app',review=!!document.querySelector('script[data-review]'),$=id=>document.getElementById(id),status=$('learning-status'),token=()=>sessionStorage.getItem('materialinsel-session')||'';
let tasks=[],enabled=false,busy=false;
const say=t=>status.textContent=t;
async function call(path,{method='GET',body}={}){const r=await fetch(API+path,{method,headers:{...(token()?{Authorization:'Bearer '+token()}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});let d;try{d=await r.json()}catch{throw Error('Der Server ist gerade nicht erreichbar. Bitte später versuchen.')}if(!r.ok)throw Error(d.error||'Die Anfrage ist fehlgeschlagen.');return d}
function node(tag,text,parent){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(parent)parent.append(n);return n}
async function fileDownload(id){const r=await fetch(API+'/learning/submissions/'+encodeURIComponent(id)+'/file',{headers:{Authorization:'Bearer '+token()}});if(!r.ok)throw Error('Datei nicht verfügbar.');const blob=await r.blob(),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download='loesung.'+(blob.type.includes('pdf')?'pdf':blob.type.includes('png')?'png':'jpg');a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
async function submissions(){if(!token())return;try{const d=await call(review?'/admin/learning/submissions':'/learning/submissions');$('submissions').replaceChildren();if(!d.submissions.length)node('p','Noch keine Abgaben vorhanden.', $('submissions'));for(const s of d.submissions){const a=node('article',undefined,$('submissions'));a.className='submission';node('h3',(tasks.find(t=>t.id===s.task)?.title||s.task)+' · '+s.part,a);node('p',new Date(s.created*1000).toLocaleString('de-DE')+' · Kennung '+s.id,a);const state=node('p',s.status==='reviewed'?'Von Julia geprüft und freigegeben':'Wartet auf persönliche Korrektur durch Julia',a);state.className='pending';if(s.answer){const details=node('details',undefined,a);node('summary','Eingereichte Lösung',details);node('pre',s.answer,details)}if(s.review){node('h4','Rückmeldung von Julia',a);node('p',s.review,a)}const actions=node('div',undefined,a);actions.className='actions';if(s.mime){const b=node('button','Originaldatei herunterladen',actions);b.onclick=()=>fileDownload(s.id).catch(e=>say(e.message))}if(review){const task=tasks.find(t=>t.id===s.task);if(task){const details=node('details',undefined,a);node('summary','Aufgabe und Material für deine Korrektur',details);node('pre',task.assignment,details)}const label=node('label','Deine persönliche Korrektur für die Schülerin / den Schüler',a),input=node('textarea',undefined,label);input.maxLength=10000;input.value=s.review||'';input.placeholder='Schreibe hier deine persönliche Korrektur und Hinweise zum Weiterlernen.';const approve=node('button',s.status==='reviewed'?'Korrektur aktualisieren':'Geprüfte Rückmeldung freigeben',a);const checkLabel=node('label',' Originalabgabe geprüft und persönliche Korrektur fertiggestellt',a),check=node('input');check.type='checkbox';checkLabel.prepend(check);approve.disabled=true;check.onchange=()=>approve.disabled=!check.checked;approve.onclick=async()=>{approve.disabled=true;try{await call('/admin/learning/submissions/'+s.id,{method:'PATCH',body:{review:input.value}});say('Rückmeldung freigegeben.');await submissions()}catch(e){say(e.message)}finally{approve.disabled=!check.checked}}}const del=node('button','Abgabe löschen',actions);del.onclick=async()=>{if(!confirm('Abgabe einschließlich Datei und Rückmeldung endgültig löschen?'))return;try{await call('/learning/submissions/'+s.id,{method:'DELETE',body:{}});await submissions();say('Abgabe gelöscht.')}catch(e){say(e.message)}}}}catch(e){say(e.message)}}
$('refresh-learning').onclick=submissions;
async function init(){try{const d=await call('/learning/tasks');tasks=d.tasks;enabled=d.enabled;if(review){await submissions();return}for(const state of [...new Set(tasks.map(t=>t.state))]){const o=node('option',state,$('learning-state'));o.value=state}$('learning-state').onchange=()=>{$('learning-task').replaceChildren(new Option('Bitte Heft wählen',''));for(const t of tasks.filter(t=>t.state===$('learning-state').value))$('learning-task').add(new Option(t.title+' · '+t.qualification+' · '+t.year,t.id));$('learning-task').disabled=!$('learning-state').value;$('learning-assignment').hidden=true};$('learning-task').onchange=()=>{const t=tasks.find(t=>t.id===$('learning-task').value);$('assignment-text').textContent=t?.assignment||'';$('learning-assignment').hidden=!t};$('login-hint').hidden=!!token();$('learning-login').onclick=()=>sessionStorage.setItem('materialinsel-return','/eltern-schueler/lernhilfe/');$('submit-learning').disabled=!enabled||!token();say(enabled?'Wähle deine Aufgabe. Deine Rückmeldung erscheint erst nach Julias Freigabe.':'Die Abgabe ist vorübergehend nicht verfügbar.');await submissions()}catch(e){say(e.message)}}
if(!review){$('clear-file').onclick=()=>$('learning-file').value='';$('learning-form').onsubmit=async e=>{e.preventDefault();if(busy||!enabled)return;const file=$('learning-file').files[0],text=$('learning-text').value.trim();if(Boolean(file)===Boolean(text)){say('Bitte entweder Text oder eine Datei abgeben.');return}if(file&&file.size>4*1024*1024){say('Die Datei darf maximal 4 MB groß sein.');return}busy=true;$('submit-learning').disabled=true;say('Deine Lösung wird eingereicht. Bitte dieses Fenster offen lassen.');try{const body={task:$('learning-task').value,part:$('learning-part').value,text,consent:$('learning-consent').checked};if(file){const data=await new Promise((res,rej)=>{const reader=new FileReader();reader.onload=()=>res(reader.result.split(',')[1]);reader.onerror=()=>rej(Error('Datei nicht lesbar.'));reader.readAsDataURL(file)});body.file={type:file.type,data}}await call('/learning/submissions',{method:'POST',body});say('Abgabe eingegangen. Julia prüft und korrigiert deine Lösung persönlich. Anschließend gibt sie deine Rückmeldung frei.');$('learning-text').value='';$('learning-file').value='';$('learning-consent').checked=false;await submissions()}catch(e){say(e.message)}finally{busy=false;$('submit-learning').disabled=!enabled||!token()}}}init();
})();
