(() => {
 const book='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M12 5C8 2 3 3 2 4v15c3-2 7-1 10 1 3-2 7-3 10-1V4c-3-2-7-1-10 1v15"/><path d="M5 7h4M5 10h4M15 7h4M15 10h4"/></svg>';
 const header=document.createElement('header');header.className='site-header';
 header.innerHTML=`<div class="site-bar"><a class="brand" href="/">${book}<span>Materialinsel</span></a><nav id="site-navigation" aria-label="Hauptnavigation"><a href="/#faecher">Fächer & Jahrgänge</a><a href="/#arbeitsmappen">Arbeitsmappen</a><a href="/?sort=new#arbeitsmappen">Neue Materialien</a><a href="/?mode=methods#arbeitsmappen">Methodenpool</a><a href="/ueber-mich/">Über mich</a></nav><a class="account-link" data-account-link href="/konto/">Anmelden / Account anlegen</a><button class="menu-toggle" type="button" aria-label="Menü öffnen" aria-expanded="false" aria-controls="site-navigation">☰</button></div>`;
 document.body.prepend(header);
 const toggle=header.querySelector('.menu-toggle');toggle.onclick=()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Menü schließen':'Menü öffnen');header.classList.toggle('menu-open',open);};
 header.querySelector('nav').addEventListener('click',()=>{toggle.setAttribute('aria-expanded','false');header.classList.remove('menu-open');});
 let footer=document.querySelector('footer');if(!footer){footer=document.createElement('footer');document.body.append(footer);}
 footer.className='site-footer';footer.innerHTML=`<div><a class="brand" href="/">${book}<span>Materialinsel</span></a><p>Arbeitsmappen, Quellen und Ideen für einen Unterricht, der Fragen öffnet.</p><small>© Julia Sonnenwald · Materialinsel</small></div><div><strong>Entdecken</strong><a href="/#faecher">Fächer & Jahrgänge</a><a href="/#arbeitsmappen">Alle Arbeitsmappen</a><a href="/projekte/wfu-zweitzeugen/">Projekte & Kurse</a><a href="https://erinnernesr-production.up.railway.app/" target="_blank" rel="noopener">Gedenkstättenfahrten ↗</a><a href="/ueber-mich/">Über mich</a></div><div><strong>Lehrkräftebereich</strong><a href="/konto/">Anmelden & Registrieren</a><a href="/konto/admin.html">Adminbereich</a><a href="/impressum/">Impressum</a><a href="/konto/datenschutz.html">Datenschutzhinweise</a><a href="mailto:julia.sonnenwald@europaschule-rheinberg.de">Kontakt</a></div>`;
})();
